[1999] Fix trainees with old subjects
DFE-Digital/register-trainee-teachers pull request #1068
Opened 2021-06-25 14:28 UTC by darokel

### Context

- https://trello.com/c/hoWiJpQH/1999-fix-the-existing-trainees-subjects-in-prod

### Changes proposed in this pull request

- Create a data migration to fix trainees in prod with old subjects based on the spreadsheet by Andrew

### Guidance to review

- Nothing this is a one time and irreversible data migration

2021-06-25 14:28 UTC, darokel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the existing trainees subjects in prod](https://trello.com/c/hoWiJpQH/1999-fix-the-existing-trainees-subjects-in-prod)

2021-06-28 10:54 UTC, jhenderson requested changes

2021-06-28 10:54 UTC, jhenderson commented on db/data/20210625135853_update_trainee_subjects.rb
> +    "Religious education" => Dttp::CodeSets::CourseSubjects::RELIGIOUS_EDUCATION_DTTP_ID,
```suggestion
    "Religious education" => Dttp::CodeSets::CourseSubjects::RELIGIOUS_STUDIES,
```

2021-06-28 13:16 UTC, jhenderson approved these changes

2021-06-28 13:21 UTC, merged