[2181] Update trainee start date question
DFE-Digital/register-trainee-teachers pull request #1126
Opened 2021-07-12 15:43 UTC by mooktakim

### Context

https://trello.com/c/4eHJSmEg/2181-update-trainee-start-date-question

### Changes proposed in this pull request

* When course start date is set, an extra question is asked on training details form, to use the course start date or the enter a start date manually
* Option is not shown if no course start date is set

### Guidance to review

* Add new trainee, complete course section, go to "Trainee start date and ID" section
* Add new trainee, go to "Trainee start date and ID", you should not get option

2021-07-12 15:43 UTC, mooktakim commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update trainee start date question](https://trello.com/c/4eHJSmEg/2181-update-trainee-start-date-question)

2021-07-13 11:11 UTC, AbigailMcP reviewed
Nice 👍 just a couple of comments inline! Main one being the error handling for when no course start date is set.

2021-07-13 11:11 UTC, AbigailMcP commented on app/forms/training_details_form.rb
> +    course_start_date == trainee.commencement_date ? "course" : "manual"
Can we pull these magic strings into a constant?

2021-07-13 11:11 UTC, AbigailMcP commented on app/forms/training_details_form.rb
> +  def course_start_date_str
This form class isn't really the right place for this view formatting.

2021-07-14 10:42 UTC, AbigailMcP approved these changes
Nooice - ready for product review!

2021-07-15 10:26 UTC, edwardhorsford commented on app/views/trainees/start_dates/edit.html.erb
> +        text: t("views.forms.start_dates.commencement_date.label"), size: "l", tag: "h1"
Is this size and `h1` correct? I don't see this output in the rendered markup - but we don't want an h1 on the date field.

2021-07-15 10:33 UTC, edwardhorsford requested changes
A few bugs:

1: Double errors showing
![Screenshot 2021-07-15 at 11 21 42](https://user-images.githubusercontent.com/2204224/125774186-892ae6ef-4471-40b5-bbfa-9e3efe576eb6.png)

2. Conditional question showing in error when the parent hasn't be asked
![Screenshot 2021-07-15 at 11 22 02](https://user-images.githubusercontent.com/2204224/125774216-72f88a40-80a9-4052-9594-2962ea7099d9.png)

3. Page title not prepended with `Error: `

2021-07-15 10:33 UTC, edwardhorsford commented on app/views/trainees/training_details/edit.html.erb
> +            }, hint: { text: t("views.forms.training_details.commencement_date.hint2", year: Time.zone.now.year) } %>
I wonder if this translation name could be more descriptive vs having `2` appended.

2021-07-15 10:33 UTC, edwardhorsford commented on config/locales/en.yml
> +        commencement_date_option:
```suggestion
        commencement_date_radio_option:
```

thoughts?

2021-07-15 10:33 UTC, edwardhorsford commented on config/locales/en.yml
> +              inclusion: Select a start date option
```suggestion
              inclusion: Choose a start date
```

2021-07-16 09:25 UTC, edwardhorsford commented
The link for the error message isn't correctly linked to the field
![Screenshot 2021-07-16 at 10 23 34](https://user-images.githubusercontent.com/2204224/125925456-6123c021-5c41-4326-9432-98bd7fe179ce.png)

2021-07-16 14:06 UTC, merged