[2262] Change link and link text for early years bursary
DFE-Digital/register-trainee-teachers pull request #1143
Opened 2021-07-14 13:32 UTC by avinhurry

### Context

Changing the link and link text for any bursary applying to an early years route (we have two at the moment).

### Guidance to review

- Add a new trainee on the`Early years (postgrad)`
- Click on the funding section
- Select `Now Teach` and continue
- Check that the correct link and link text appears as per the Trello ticket

- Repeat for a trainee on the `Early years (salaried) route`. 
You may have to add `early_years_salaried: true` locally and run the seeds again.

2021-07-14 13:33 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [EY bursaries - link text and href update](https://trello.com/c/Hu0kjR0l/2262-ey-bursaries-link-text-and-href-update)

2021-07-14 13:49 UTC, AbigailMcP requested changes
Last sentence on the card: "All other bursaries should remain unchanged."

Non-EY bursaries should have the old guidance link text and href.

2021-07-14 15:22 UTC, AbigailMcP approved these changes
🌮

2021-07-16 15:20 UTC, bbelward commented
Reviewed! Flagging that the early years salaried route wasn't available on this deployment, so I only tested for early years postgrad - but the link was correct there.

2021-07-16 15:24 UTC, merged