2290 adding synonyms to degree datasets
DFE-Digital/register-trainee-teachers pull request #1176
Opened 2021-07-22 14:14 UTC by AbigailMcP

### Context

https://trello.com/c/AnFnNO3t/2290-spike-adding-synonyms-to-our-data-sets

### Changes proposed in this pull request

- Adds synonyms to our subject, degree type and institution datasets

### Guidance to review

Check the Trello card for search queries to test out.

2021-07-23 13:26 UTC, edwardhorsford requested changes

2021-07-23 13:26 UTC, edwardhorsford commented on app/lib/dttp/code_sets/degree_subjects.rb
> +          synonyms: ["pure mathematics"],
```suggestion
          synonyms: ["pure maths"],
```

😉

2021-07-23 14:09 UTC, AbigailMcP commented on app/lib/dttp/code_sets/degree_subjects.rb
> +          synonyms: ["pure mathematics"],
oh fineeee 🙄

2021-07-27 16:34 UTC, defong approved these changes
Let's get this tin!

2021-07-28 09:13 UTC, edwardhorsford approved these changes

2021-07-28 09:14 UTC, merged