Set BLAZER_DATABASE_URL environment variable
DFE-Digital/register-trainee-teachers pull request #1225
Opened 2021-08-02 16:02 UTC by vigneshmsft

### Context

#1220 requires `BLAZER_DATABASE_URL`

### Changes proposed in this pull request

Create a separate service-key for database connection
Configure BLAZER_DATABASE_URL

2021-08-02 16:06 UTC, gpeng requested changes

2021-08-02 16:06 UTC, gpeng commented on terraform/modules/paas/main.tf
> +resource "cloudfoundry_service_key" "postgres-blazer-key" {
Do we need the quotes here? They're not used in the rest of the file.

2021-08-02 16:06 UTC, gpeng commented on terraform/modules/paas/variables.tf
> +    BLAZER_DATABASE_URL = cloudfoundry_service_key.postgres-blazer-key.credentials.uri
This needs the settings prefix
```suggestion
    SETTINGS__BLAZER_DATABASE_URL = cloudfoundry_service_key.postgres-blazer-key.credentials.uri
```

2021-08-02 16:17 UTC, gpeng approved these changes

2021-08-02 16:29 UTC, merged

2021-08-03 09:06 UTC, vigneshmsft commented
![](https://github.trello.services/images/mini-trello-icon.png) [Assign a valid connection string for BLAZER_DATABASE_URL](https://trello.com/c/TrYSPW1A/2406-assign-a-valid-connection-string-for-blazerdatabaseurl)