2328 course study mode question publish trainees
DFE-Digital/register-trainee-teachers pull request #1249
Opened 2021-08-06 17:34 UTC by avinhurry

### Context

### Changes proposed in this pull request

### Guidance to review

2021-08-06 17:46 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [[L] Course study mode question - Publish trainees](https://trello.com/c/XBDN1FnL/2328-l-course-study-mode-question-publish-trainees)

2021-08-11 10:00 UTC, mooktakim requested changes
Couple of comments

2021-08-11 10:27 UTC, avinhurry commented on app/controllers/concerns/publish_course_next_path.rb
> +  end
study_mode will never be nil

2021-08-12 14:33 UTC, mooktakim approved these changes
Looks good

2021-08-16 09:14 UTC, bbelward commented
Hey @avinhurry, I'm getting the form step, but study mode doesn't show up on the confirm page 😢  Tried it on multiple courses, also varying between full time and part time options. 
![2328studymode](https://user-images.githubusercontent.com/31930137/129540152-f938626e-b7d7-4806-9669-8f3877f5521f.gif)

2021-08-16 10:23 UTC, avinhurry commented
🤔 @bbelward, I can't seem to replicate that. Can you let me know when you have time for a chat please?

2021-08-16 12:55 UTC, merged