2529 publish course issue with duplicate course codes
DFE-Digital/register-trainee-teachers pull request #1306
Opened 2021-08-19 15:03 UTC by defong

### Context

### Changes proposed in this pull request

### Guidance to review

2021-08-19 16:07 UTC, defong commented
![](https://github.trello.services/images/mini-trello-icon.png) [Publish course issue with duplicate course codes](https://trello.com/c/BhzyJFSp/2529-publish-course-issue-with-duplicate-course-codes)

2021-08-20 11:11 UTC, gpeng requested changes

2021-08-20 11:11 UTC, gpeng commented on spec/components/course_details/view_spec.rb
> +        it "renders the incorrect course details" do
```suggestion
        it "doesn't render the incorrect course details" do
```

2021-08-20 14:52 UTC, gpeng approved these changes

2021-08-23 12:30 UTC, merged