[2809] Redirect to publish course details page when course code is not found
DFE-Digital/register-trainee-teachers pull request #1507
Opened 2021-09-24 14:55 UTC by archferns

### Context
fixes https://trello.com/c/CREaXO17/2809-changing-course-details-to-another-course-not-listed-crashes-the-course-details-page

### Changes proposed in this pull request

### Guidance to review

2021-09-24 14:55 UTC, archferns commented
![](https://github.trello.services/images/mini-trello-icon.png) [Changing course details to "Another course not listed" crashes the course details page](https://trello.com/c/CREaXO17/2809-changing-course-details-to-another-course-not-listed-crashes-the-course-details-page)

2021-09-24 16:02 UTC, defong commented
![image](https://user-images.githubusercontent.com/470137/134705758-c16e73c6-8898-419d-8753-de98df6175a8.png)
Can we have something like that but with out the link
![image](https://user-images.githubusercontent.com/470137/134705911-76fefdd7-68b5-484d-bfb9-fff8df7c9674.png)

2021-09-27 08:00 UTC, archferns commented
Fixed in https://github.com/DFE-Digital/register-trainee-teachers/pull/1507/commits/5c3aa9d88500247f657316a011e3c10fb6eab9f4 by surfacing the apply application's course code.
![image](https://user-images.githubusercontent.com/910019/134868023-7d1c0018-3d27-43fb-a706-e9c9ed55ef98.png)

2021-09-27 10:25 UTC, defong requested changes
This is looking like it need a bit more content remedy more than anything else.

A 4 characters identifier without any else seems odd, given that the same identifier can be referred to an actual course name on all 3 service Find / Publish / Apply, it kinda breaks continuity from all 3 service.

https://www.find-postgraduate-teacher-training.service.gov.uk/results

![image](https://user-images.githubusercontent.com/470137/134891306-209f7df4-77c4-47f8-940f-0ab31a1b6dda.png)


Also casing of route.

@gregknight1 can you help us in this pickle.

2021-09-27 14:47 UTC, gregknight1 commented
@defong If I've understood correctly - yes we should have the course name included with the 4 char identifier. And the route should be lower case.

2021-09-28 09:01 UTC, defong approved these changes

2021-09-28 10:25 UTC, merged