[2814] Make sure published course is scope to trainee's provider
DFE-Digital/register-trainee-teachers pull request #1523
Opened 2021-09-28 12:57 UTC by darokel

### Context

- https://trello.com/c/jrrECRv9/2814-fix-missing-course-subject-for-trainee-301-in-prod

### Changes proposed in this pull request

Some providers will list courses with the same code. Make sure `#published_course` on the `Trainee` is scope to their own provider

### Guidance to review

2021-09-28 12:58 UTC, darokel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix missing course subject for trainee 301 in prod](https://trello.com/c/jrrECRv9/2814-fix-missing-course-subject-for-trainee-301-in-prod)

2021-09-28 13:14 UTC, AbigailMcP approved these changes

2021-09-28 15:03 UTC, AbigailMcP requested changes
Hmm looks like this causes a problem with preloading (unable to preload published_courses since it's now instance-dependent)

Line 88 in trainees controller:     

```
policy_scope(Trainee.includes(:published_course).ordered_by_drafts.public_send(sort_scope))
```

2021-09-29 14:16 UTC, AbigailMcP approved these changes

2021-09-29 15:15 UTC, merged