353 Add edit programme details confirmation page
DFE-Digital/register-trainee-teachers pull request #160
Opened 2020-11-10 15:54 UTC by SamJamCul

### Context
https://trello.com/c/MAQqgkeA/353-s-confirm-trainee-programme-details-page

### Changes proposed in this pull request
* Added a confirmation page and summary card after the edit programme details section

### Guidance to review

![image](https://user-images.githubusercontent.com/25597009/98697617-05c2ec00-236d-11eb-8573-e8c9dd413803.png)

2020-11-10 16:02 UTC, SamJamCul commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Confirm Trainee Programme Details Page](https://trello.com/c/MAQqgkeA/353-s-confirm-trainee-programme-details-page)

2020-11-10 21:32 UTC, defong requested changes
> ### Guidance to review
> 
> ![image](https://user-images.githubusercontent.com/25597009/98697617-05c2ec00-236d-11eb-8573-e8c9dd413803.png)

![image](https://user-images.githubusercontent.com/470137/98735761-d2e41c80-239b-11eb-84bb-a38ac483df23.png)

These two looks like it needs addressing
- [ ] title
- [x] date format

2020-11-10 21:32 UTC, defong commented on spec/features/trainees/edit_programme_details_spec.rb
> +    and_confirm_my_details
```suggestion
    and_i_confirm_my_details
```

2020-11-10 21:32 UTC, defong commented on spec/features/trainees/edit_programme_details_spec.rb
> +  def and_confirm_my_details
```suggestion
  def and_i_confirm_my_details
```

2020-11-11 14:26 UTC, SamJamCul commented on spec/features/trainees/edit_programme_details_spec.rb
> +  def and_confirm_my_details
Done

2020-11-11 14:27 UTC, SamJamCul commented on spec/features/trainees/edit_programme_details_spec.rb
> +    and_confirm_my_details
done

2020-11-11 14:44 UTC, SamJamCul commented
@defong I checked other confirmation cards, and none of them have this dynamic titling based on the Assessment Only route thing - I think this might be something we have to add later, or as another card at least?

2020-11-11 15:37 UTC, defong commented
> @defong I checked other confirmation cards, and none of them have this dynamic titling based on the Assessment Only route thing - I think this might be something we have to add later, or as another card at least?

yeah... I was comparing it with prototype... I guess we can card it for later

2020-11-11 15:38 UTC, defong approved these changes

2020-11-11 16:09 UTC, darokel approved these changes

2020-11-11 16:19 UTC, merged