[3150] Re-structure providers sub tab navigation
DFE-Digital/register-trainee-teachers pull request #1707
Opened 2021-11-03 16:19 UTC by jhenderson

### Context
https://trello.com/c/vBfdbZOT/3150-s-re-structure-providers-sub-tab-navigation

### Changes proposed in this pull request
- Replace providers sub tab with a new version that lists "Registered users" and "DTTP users"

### Guidance to review
- Make sure your user record has the field `system_admin` set to `true`
- Visit the the `/system-admin/providers`
- Click on a provider
- You should see the follow screen:

<img width="990" alt="Screenshot 2021-11-03 at 16 18 47" src="https://user-images.githubusercontent.com/28728/140100182-40198a65-9cae-4669-bd42-d033adf1bd38.png">

2021-11-03 16:19 UTC, jhenderson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Re-structure providers sub tab navigation](https://trello.com/c/vBfdbZOT/3150-s-re-structure-providers-sub-tab-navigation)

2021-11-04 10:49 UTC, mooktakim requested changes

2021-11-04 10:49 UTC, mooktakim commented on app/views/system_admin/dttp_users/index.html.erb
> +]) %>
This should be a partial as its shared by the `show.html.erb` page and any future pages.

2021-11-04 10:49 UTC, mooktakim commented on app/views/system_admin/providers/show.html.erb
> +]) %>
The users link text is different from `index.html.erb` page. should be partial.

2021-11-05 12:00 UTC, mooktakim approved these changes

2021-11-09 12:27 UTC, merged