[3234] Course years UI
DFE-Digital/register-trainee-teachers pull request #1761
Opened 2021-11-23 15:54 UTC by mooktakim

### Context

https://trello.com/c/6me29388/3234-l-course-years-ui

### Changes proposed in this pull request

* Change course year page added
* Publish course details form courses are filtered based on the `year` query param
* `@course_year` defaults to `@trainee.published_course.recruitment_cycle_year` if available otherwise to `Settings.current_default_course_year`.
* If `year` param is invalid, redirected to change course year page.

### Guidance to review

*  Add provider-led (postgrad) trainee, go to Course details section.

2021-11-23 15:55 UTC, mooktakim commented
![](https://github.trello.services/images/mini-trello-icon.png) [[L] Course years UI](https://trello.com/c/6me29388/3234-l-course-years-ui)

2021-11-25 13:57 UTC, archferns approved these changes
Looks and works great, would be nice if we can configure seed courses to have all three years, but not a blocker.

2021-11-29 18:09 UTC, bbelward commented
A few things to clarify, first 1 is probably to do with seed data, but just to confirm - should I expect to see publish course dates for 2020-21 year or 2022-23 years?
![Screenshot 2021-11-29 at 18 05 32](https://user-images.githubusercontent.com/31930137/143920459-354d65c1-31d4-4284-84b5-894a28022a27.png)
![Screenshot 2021-11-29 at 18 05 23](https://user-images.githubusercontent.com/31930137/143920469-c7e80550-9f9f-4962-9e71-ab820d1933db.png)

2021-11-29 18:12 UTC, bbelward commented
Secondly, the date validation for manual course entry isn't linked to the selected year. 
Scenario: 
1. select 2020-21 start year 
2. manually enter course details with start date in 2021 and end date in 2022 
3. it accepts this even though I select 2020-21 previously 

If it's going to be a lot of work to add this validation, I expect it's only an edge case. @edwardhorsford do you think this is something we should fix immediately or something that can happen later?

2021-11-29 18:20 UTC, bbelward commented
finally, just want to confirm the correct URL slugs. On the trello card it states: * The URL of the index page could have `?year=2022` or `/edit/2022`
when I go in, I see `course-years/edit` and then `edit?year=XXXX` but I don't know if that's the index page?

2021-11-29 18:22 UTC, bbelward commented
successful test scenarios: 
1. created PL postgrad trainee and could see the appropriate screens and make the appropriate changes 
2. also review an apply import trainee and was able to view the correct years screens 

So the things to confirm before merging are: 

1. is lack of courses for other years due to seed data 
2. do we care about date validation for manual course entry? 
3. are the URL structures correct?

2021-11-30 09:42 UTC, edwardhorsford requested changes
Something is wrong with the setup of these radios. If I click the label for `2020 to 2021`, the first radio is focused again - the labels do not seem to be correctly associated with the radios.

<img width="875" alt="Screenshot 2021-11-30 at 09 41 16" src="https://user-images.githubusercontent.com/2204224/144023036-13879bb2-fe1a-4e87-b212-43c878fdc8f7.png">

2021-11-30 09:46 UTC, edwardhorsford commented
> If it's going to be a lot of work to add this validation, I expect it's only an edge case. @edwardhorsford do you think this is something we should fix immediately or something that can happen later?

I'd be tempted to leave it - accept what the user gives us.

---

If there are no courses for a chosen year, I think we should go directly to manual entry - showing a page with a single radio seems pointless.

---

When going to the year selection page, if there's an existing year or a default year, that year should be pre-selected
<img width="840" alt="Screenshot 2021-11-30 at 09 45 04" src="https://user-images.githubusercontent.com/2204224/144023750-1bdeb876-acb9-4cdd-80af-b6d08dfeb8a8.png">

---

Can we seed courses from other years? I only see courses for one year, which makes testing across years hard.

2021-11-30 09:49 UTC, edwardhorsford commented
Bug. From this page if I continued without picking 'another', I got no error validation. It went through as if I'd picking a specific course (I presume this was a course I had previously picked on another year).

<img width="882" alt="Screenshot 2021-11-30 at 09 47 48" src="https://user-images.githubusercontent.com/2204224/144024378-8c08bf8d-b928-4857-981a-397870c88fc5.png">

Two issues here:
* After changing year, we should be deleting any course details / course reference we have
* No validation in that page's scenario - though I suspect it's because the validator is checking if a course is selected.

2021-11-30 10:05 UTC, edwardhorsford commented
Please can the error message say `Select a course year`

2021-11-30 11:24 UTC, mooktakim commented
@bbelward 
Unable to reply to each comment, I'll try to answer here:
- The seed data on this review app doesn't have courses for other years. I'll try to seed it with other years.
- The years form is only used to filter the courses list, it does not change the manual course form. We don't store the start year.
- The URL parameter is for the publish courses form, not years form. As that's where it is used to filter the courses list.

2021-12-02 10:00 UTC, edwardhorsford commented
Looking much better!

Only one remaining thing that I could see - I picked a course in one year, then navigated back, and picked manual for a different year - study mode was pre-populated, which wasn't expected - as I thought we would clear out the course details when changing course.

2021-12-02 15:45 UTC, edwardhorsford approved these changes

2021-12-03 10:18 UTC, merged