show not available in the export if funding not available
DFE-Digital/register-trainee-teachers pull request #1809
Opened 2021-12-08 15:08 UTC by richardpattinson

### Context

Where funding isn't available for a trainee / their course, we should show `not applicable` in the export.

### Changes proposed in this pull request

Add not available option to conditional in export.

### Guidance to review

2021-12-08 15:08 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Show 'not applicable' on export where funding isn't available](https://trello.com/c/FejjCOYw/3299-s-show-not-applicable-on-export-where-funding-isnt-available)

2021-12-08 16:43 UTC, gpeng requested changes

2021-12-08 16:43 UTC, gpeng commented on app/services/exports/trainee_search_data.rb
> +      elsif !FundingManager.new(trainee).funding_available?
We should make method for returning the `FundingManager` instance as this is duplicated on 139.

2021-12-09 10:03 UTC, gpeng requested changes
Also forgot to mention, can you prefix your commits with the trello ticket number. We generally do that and name the PRs with the ticket number too 😁

2021-12-09 10:03 UTC, gpeng commented on app/services/exports/trainee_search_data.rb
> +    def funding_manager(trainee)
The variable here isn't necessary. Without the `@` its scope is internal to the method so this wouldn't memoise it. We probably don't want to memorise this anyway as we'd end up with a the `FundingManager` stuck on the same trainee.
```suggestion
    def funding_manager(trainee)
      FundingManager.new(trainee)
    end
```

2021-12-11 12:42 UTC, gpeng approved these changes

2021-12-13 09:47 UTC, merged