[3296] Improve degree type option for `Higher Degree`
DFE-Digital/register-trainee-teachers pull request #1816
Opened 2021-12-10 09:53 UTC by jhenderson

### Context
[3295-substitution-phrases-for-school-search](https://trello.com/c/MBxMhgWo/3296-improve-degree-type-option-for-higher-degree)

### Changes proposed in this pull request
- Add support for hint text in autocomplete results

### Guidance to review
- Visit degree form page
- Type "postgrad" in degree type field
- Hint text should be displayed underneath "Higher Degree"

<img width="804" alt="Screenshot 2021-12-10 at 09 53 21" src="https://user-images.githubusercontent.com/28728/145554396-f2d7bac2-3172-4a65-8d22-de893cfb623c.png">

2021-12-10 10:01 UTC, jhenderson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Improve degree type option for `Higher Degree`](https://trello.com/c/MBxMhgWo/3296-improve-degree-type-option-for-higher-degree)

2021-12-10 10:55 UTC, edwardhorsford requested changes
@jhenderson We're also looking for the name of the option to change - from `Higher Degree` to `Higher degree or equivalent`

2021-12-13 15:51 UTC, edwardhorsford approved these changes

2021-12-15 10:30 UTC, mooktakim approved these changes
👍

2021-12-15 11:13 UTC, merged