[483] Added puma ssl/https and related items
DFE-Digital/register-trainee-teachers pull request #182
Opened 2020-11-18 12:33 UTC by JonF1

### Context
This is cherry-picked from Sau:
https://github.com/DFE-Digital/register-trainee-teachers/pull/126

puma ssl/https and related items

### Changes proposed in this pull request

Added puma ssl/https and related items
default port from 3000 to 5000
zeroed ip (0.0.0.0)
default from HTTP to HTTPS
enforced ssl usage as default

### Guidance to review

Ported mainly from https://github.com/DFE-Digital/publish-teacher-training/blob/master/config/puma.rb

These are the minimum security and infrastructures requirements for future work.

Port 5000 was selected to remove common default rails port collusion.

Navigate to https://localhost:5000

If you see a certificate error message on Chrome on Mac - click and type 'thisisunsafe' (i'm not joking)

2020-11-18 13:43 UTC, defong commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] Add a sign in page](https://trello.com/c/10W1RWyg/483-m-add-a-sign-in-page)

2020-11-18 14:38 UTC, darokel commented on config/settings.yml
> +nationalities:
I don't think this nationalities chunk should be in here. It may have leaked in

2020-11-18 14:39 UTC, darokel requested changes
Could we remove the nationalities list from the yaml, I don't think it should be in this PR.

2020-11-20 09:58 UTC, darokel approved these changes

2020-11-20 15:33 UTC, aliuk2012 commented on config/settings.yml
> +
end of file

2020-11-20 15:46 UTC, defong commented on config/settings.yml
> +
:+1:

2020-11-20 15:52 UTC, merged