3298 backfill course start and end dates the first time a course is used
DFE-Digital/register-trainee-teachers pull request #1837
Opened 2021-12-17 17:40 UTC by jhenderson

### Context
https://trello.com/c/5lvz3nu8/3298-l-backfill-course-start-and-end-dates-the-first-time-a-course-is-used

### Changes proposed in this pull request

### Guidance to review

### Important business

* Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

2021-12-17 18:19 UTC, jhenderson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[L] Backfill course start and end dates the first time a course is used](https://trello.com/c/5lvz3nu8/3298-l-backfill-course-start-and-end-dates-the-first-time-a-course-is-used)

2021-12-21 15:49 UTC, mooktakim approved these changes
Looks good 👍

2021-12-23 11:06 UTC, edwardhorsford requested changes
I think we should be validating that the provided start date falls in the selected academic year. At the least we shouldn't save these dates back to the course if they're outside the correct academic year.

In this PR if you have a 2021 to 2022 course and then give a start date in the 2020 to 2021 year, then the academic year for the course changes and it stops appearing in the right academic year.

2021-12-23 11:11 UTC, edwardhorsford commented on config/locales/en.yml
> +          %{cycle_year} - but we do not have the complete start and end date for it.<p>
```suggestion
          %{cycle_year} – but we do not have complete start and end dates for it.<p>
```

2021-12-23 11:13 UTC, edwardhorsford commented on config/locales/en.yml
> +          edit: ITT Dates
```suggestion
          edit: ITT dates
```

2021-12-23 11:15 UTC, edwardhorsford commented on config/locales/en.yml
> +                <p class="govuk-body govuk-hint">For example, 11 3 %{year}</p>
```suggestion
              hint_html: For example, 11 9 %{year}
            end_date:
              blank: Enter an ITT end date
              future: Enter an ITT end date closer to today
              invalid: Enter a valid ITT end date
              too_old: Enter a valid ITT end date
              before_or_same_as_start_date: The ITT end date must be after the start date
              hint_html: For example, 11 6 %{year}
```

2021-12-23 11:22 UTC, edwardhorsford commented
Suggested error messages for when start date falls in a different academic year:

In error summary:
`The ITT start date is for a different academic year than the selected course. Enter a valid date or [choose a different year]`

In the field:
`Enter a valid start date`

2021-12-30 11:15 UTC, edwardhorsford submitted a review, later dismissed
Error messages not quite right. The intention is that `choose a different year` be a link to the year picker. This might need something custom so it doesn't also sit in a link itself - I think we might have done something similar for the duplicate TraineeID check?

The message on the field is intended to be `Enter a valid start date`
<img width="1037" alt="Screenshot 2021-12-30 at 11 13 26" src="https://user-images.githubusercontent.com/2204224/147746970-4eab4002-9659-4c57-9725-9659ffe4cb0c.png">

2021-12-31 10:23 UTC, merged