[3374] Provider users many to many
DFE-Digital/register-trainee-teachers pull request #1868
Opened 2022-01-05 15:31 UTC by mooktakim

### Context

https://trello.com/c/Qzaf2eBf/3374-l-provider-users

### Changes proposed in this pull request

* Many to many relation added for `Provider` and `User` using model `ProviderUser`
* Data migration added to copy over `User.provider_id` to `ProviderUser` relationships.
* Added `User.primary_provider`, returns first provider
* `User.primary_provider` is used instead of old `User.provider`, will need to be updated when we have worked out how to choose current provider.

### Guidance to review

### Important business

* Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

2022-01-05 15:31 UTC, mooktakim commented
![](https://github.trello.services/images/mini-trello-icon.png) [[L] Provider users](https://trello.com/c/Qzaf2eBf/3374-l-provider-users)

2022-01-06 12:30 UTC, gpeng reviewed
I'm not sure about the concept of `primary_provider`. Well, I am sure that there won't be such a thing but I'm not sure how we handle the transition but I think this is going to give us a lot to change. Let's have a chat about it.

2022-01-06 15:13 UTC, gpeng requested changes

2022-01-06 15:13 UTC, gpeng commented on app/policies/trainee_policy.rb
> +      user.system_admin? ? scope.all : scope.where(provider_id: user.primary_provider&.id).kept
I don't think we should guard against nil provider here. It shouldn't happen and we should raise if it does.

2022-01-06 15:13 UTC, gpeng commented on db/schema.rb
> -  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
We've decided we want to keep this in the schema. Can you un-delete-if-icate it?

2022-01-06 15:13 UTC, gpeng commented on spec/features/system_admin/users/updating_a_user_spec.rb
> +    provider_show_page.load(id: user.primary_provider&.id)
Do we need the `&` here (and in the other places)?

2022-01-07 15:33 UTC, gpeng approved these changes

2022-01-07 15:37 UTC, merged