show start date when trainee withdraws
DFE-Digital/register-trainee-teachers pull request #1869
Opened 2022-01-05 16:49 UTC by richardpattinson

### Context

For clarity (and consistency with deferral) we should show the user the commencement date when the user withdraws a trainee and allow them to change it

### Changes proposed in this pull request

Add commencement date to withdraw flow with change link

2022-01-06 10:22 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] Show start date when trainee withdraws](https://trello.com/c/lnOODOXy/3382-m-show-start-date-when-trainee-withdraws)

2022-01-07 17:23 UTC, mooktakim requested changes
See comments

2022-01-07 17:23 UTC, mooktakim commented on app/components/withdrawal_details/view.rb
>      end
`trainee` does not need to be a method argument as you can just do `data_model.trainee`
You could add a delegate to trainee if you like.

2022-01-07 17:23 UTC, mooktakim commented on app/components/withdrawal_details/view.html.erb
> +    },
Might be good to move this to the `View` model to reduce the logic in the view.

2022-01-07 17:23 UTC, mooktakim commented on spec/components/withdrawal_details/view_preview.rb
> +      render(View.new(data_model, data_model.trainee))
Trainee is already part of data_model

2022-01-07 17:23 UTC, mooktakim commented on spec/components/withdrawal_details/view_spec.rb
> +    render_inline(described_class.new(data_model, trainee))
Trainee is already part of data_model

2022-01-12 10:22 UTC, mooktakim approved these changes
👍

2022-01-12 11:31 UTC, merged