[475] Update canonical meta tag
DFE-Digital/register-trainee-teachers pull request #189
Opened 2020-11-18 20:21 UTC by dankmitchell

### Context
SEO - Canonical meta tag

### Changes proposed in this pull request
Update to canonical meta tag to the production domain

### Guidance to review
🚢

2020-11-18 20:21 UTC, dankmitchell commented
![](https://github.trello.services/images/mini-trello-icon.png) [update canonical link](https://trello.com/c/oreldEqt/475-update-canonical-link)

2020-11-18 20:57 UTC, defong requested changes

2020-11-18 20:57 UTC, defong commented on config/initializers/canonical_rails.rb
> +  config.host = "www.register-trainee-teachers.eduation.gov.uk"
```suggestion
  config.host = "www.register-trainee-teachers.education.gov.uk"
```

2020-11-18 21:05 UTC, defong approved these changes
Keeping it fun

2020-11-18 21:16 UTC, defong commented on config/application.rb
> +    config.session_store :cookie_store, key: '_register_trainee_teachers_session'
```suggestion
    config.session_store :cookie_store, key: "_register_trainee_teachers_session"
```

2020-11-19 09:34 UTC, avinhurry approved these changes

2020-11-19 09:37 UTC, merged