[3508] current_user support for multiple organisations
DFE-Digital/register-trainee-teachers pull request #1968
Opened 2022-01-28 17:28 UTC by gpeng

### Context

Users can now be associated with any combination of multiple providers or lead schools. The associations have been created but we're still not supporting this in the UI. Ultimately when a user logs in they should either see the correct context (either lead school or provider) if they have only one organisation or be given the opportunity to choose which context they want to work in.

### Changes proposed in this pull request

* Add support for setting the current organisation context and passing that around with current_user
* Add a multi org persona for testing
* Add a feature flag to disable this in production until it's complete

There is still work to do with this before it is ready. Still to do:

* lead school view should be read only. The policy has been updated but we're not hiding any of the change links etc
* a component to allow the user to switch their organisation context
* back link and nav hiding on the organisations#index page when a user first logs in
* some inevitable snagging

### Guidance to review

Most importantly at this stage we're checking that the organisation context displays the correct trainees for that organisation. Also that when we turn the feature flag off everything still works and the multi-org stuff doesn't kick in anywhere.

The TraineePolicy has gotten a little bit out of hand as we've mixed concerns a bit and included trainee state transition logic. This has made the tests a bit sprawling. We should maybe address that in the future but I've left it for now.

Removing `current_user.primary_provider` has caused 'a lot ™️' of changes. I've tried to keep those contained in one commit. Might be best to review one commit at a time. Sorry 😬 

### Important business

* Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

2022-02-01 09:46 UTC, jhenderson requested changes
Looks good. 👍  Left some minor feedback and request changes.

2022-02-01 14:20 UTC, gpeng commented on app/controllers/system_admin/users_controller.rb
> +      provider
Didn't we decide a while back to prefer memoized accessors over before actions? We've not been super consistent with it though.

2022-02-01 14:26 UTC, gpeng commented on app/controllers/pages_controller.rb
> +      if FeatureService.enabled?(:user_can_have_multiple_organisations) && (current_user.organisation.nil? && !current_user.system_admin?)
👍

2022-02-01 14:28 UTC, gpeng commented on app/models/dfe_sign_in_user.rb
> +    session.destroy
We've got some extra keys in there, particularly the organisation context one, that we want to clear when the user logs out so I figured we should just clear the whole session. Without this when the user logs back in they don't get the organisation picker as the context is still set from the previous session.

2022-02-01 14:30 UTC, gpeng commented
Thanks @jhenderson I've addressed your feedback in the fixup commits (I'll rebase them in when you're happy with 'em). Still need to figure out how to make sonarcloud go away though 🤫

2022-02-03 16:11 UTC, jhenderson approved these changes

2022-02-04 11:28 UTC, mooktakim commented
![](https://github.trello.services/images/mini-trello-icon.png) [current_user support for multiple organisations](https://trello.com/c/NNKrZru7/3508-currentuser-support-for-multiple-organisations)

2022-02-04 15:24 UTC, jhenderson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Main navigation should be hidden when a user has no organisation context set](https://trello.com/c/YyI7oCis/3602-s-main-navigation-should-be-hidden-when-a-user-has-no-organisation-context-set)

2022-02-10 09:53 UTC, merged