[3772] trainee id validation allows duplicates if trainee inactive
DFE-Digital/register-trainee-teachers pull request #1977
Opened 2022-02-01 14:54 UTC by richardpattinson

### Context

If a trainee is inactive (withdrawn or awarded in a previous cycle) we should be able to create a duplicate of it using the same trainee_id.

2022-02-01 15:01 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Trainee ID validation - allow same ID if trainee isn't active](https://trello.com/c/206EBZQh/3572-trainee-id-validation-allow-same-id-if-trainee-isnt-active)

2022-02-02 12:04 UTC, jhenderson requested changes
Looking good, just two request changes.

2022-02-02 12:04 UTC, jhenderson commented on spec/forms/training_details_form_spec.rb
> +        let!(:existing_trainee) { create(:trainee, trainee_id: "Test123", state: "recommended_for_award") }
It appears that adding the state doesn't make a difference to the outcome of the test because they both have the same `trainee_id`.

2022-02-08 11:13 UTC, jhenderson approved these changes
Looks good. I've make two suggestions which I recommend before merging.

2022-02-08 11:13 UTC, jhenderson commented on spec/forms/training_details_form_spec.rb
> +          expect(existing_trainee.inactive?).to be(false)
I think you can extract this line into a separate example:
```suggestion
it "existing trainee remains active" do
  expect(existing_trainee.inactive?).to be(false)
end 
```

2022-02-08 11:13 UTC, jhenderson commented on spec/forms/training_details_form_spec.rb
> +          expect(existing_trainee.inactive?).to be(true)
Again, you can extract this line into a separate example:

```suggestion
it "existing trainee becomes inactive" do
  expect(existing_trainee.inactive?).to be(true)
end 

```

2022-02-09 13:20 UTC, merged