[480] s Add feature flags to toggle DfE Sign-In/Personas, Configure Omniauth
DFE-Digital/register-trainee-teachers pull request #206
Opened 2020-11-24 16:01 UTC by JonF1

### Context
* https://trello.com/c/qpMzJ4sp/480-s-feature-flags-and-omniauth-configured-to-allow-dfe-sign-in-personas-depending-on-env

We need to be able to toggle DfE Sign-In and Personas depending on environment. This PR forks the two and configures omni auth so that that can work. 
### Changes proposed in this pull request

Adds feature flags
Configures omni auth to have /auth/developer, callback and then not need token
Fixed and deleted tests

### Guidance to review
Toggle DfE Sign-In/Personas and go through user/developer journey.

2020-11-24 20:15 UTC, defong commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] feature flags and omniauth configured to allow DfE Sign-In/Personas depending on env](https://trello.com/c/qpMzJ4sp/480-s-feature-flags-and-omniauth-configured-to-allow-dfe-sign-in-personas-depending-on-env)

2020-11-25 09:28 UTC, aliuk2012 commented on app/components/personas/view.html.erb
> +<% end %>
cant we use govuk form builder? 

Also end of file ;)

2020-11-25 09:40 UTC, aliuk2012 requested changes
A few minor things otherwise looks good to me

2020-11-25 11:57 UTC, aliuk2012 approved these changes

2020-11-25 12:47 UTC, merged