[3677] Cohort filter homepage changes
DFE-Digital/register-trainee-teachers pull request #2212
Opened 2022-04-05 11:28 UTC by AbigailMcP

### Context

https://trello.com/c/xs84EsrH/3677-cohort-filter-homepage-changes

### Changes proposed in this pull request

- Updates to HomeView to return counts relating to current cohort
- Updates to home.html.erb to add extra links to current and future cohorts
- Updates to Badges component to link to current cohort filtered views

### Guidance to review

- Check that there's "View next year's trainees" link on the homepage that links to the registered trainees page with 'Next year's' filter selected.
- Check that the count is correct on the link
- Check that there's a "View current trainees" link on the homepage that links to the registered trainees page with 'Current' filter selected
- Check that the boxes are only referring to the current trainee counts
- Check that they all link to the registered trainees page with 'current' plus the correct state selected

### Important business

* Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

2022-04-06 13:58 UTC, archferns approved these changes

2022-04-07 11:12 UTC, ralph-hawkins requested changes
Looks good, just a couple of very small things.

2022-04-07 11:12 UTC, ralph-hawkins commented on app/views/pages/home.html.erb
> +      <% end %>
I don't think we need the condition on this link.

Its probably rare enough that we don't need to worry, but can you put it around line 78 to 95, so we also hide the 'Current trainee' heading and status boxes.

2022-04-07 11:12 UTC, ralph-hawkins commented on app/views/pages/home.html.erb
>      </ul>
This doesn't need to be a list as there will only ever be one item.

2022-04-13 08:20 UTC, AbigailMcP commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cohort filter - homepage changes](https://trello.com/c/xs84EsrH/3677-cohort-filter-homepage-changes)

2022-05-20 10:49 UTC, AbigailMcP commented
We're re-working this, and probably won't need this PR. Closing for now.

2022-05-20 10:49 UTC, closed without merging