3943 Add read only function for provider users
DFE-Digital/register-trainee-teachers pull request #2239
Opened 2022-04-07 15:49 UTC by richardpattinson

### Context

Add a read only boolean to the provider users model and do not allow editing of records where this flag is enabled.

https://trello.com/c/LGmo5QAe/3943-read-only-admin-access

### Changes proposed in this pull request

Migration to add read only boolean to users model; add check in TraineePolicy to check for this boolean and decide if user can edit records.

### Guidance to review

Create a user with read_only set to true and check you cannot edit records. 

### Important business

* Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

2022-04-08 08:28 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Read only admin access](https://trello.com/c/LGmo5QAe/3943-read-only-admin-access)

2022-04-08 13:31 UTC, gpeng commented
Looks good. I've set Agatha Baker in the review app to be a read-only administrator for product review.

2022-04-11 16:01 UTC, edwardhorsford requested changes
Looking good!

There are a few places in the UI where we still offer to let edits happen - though the actions themselves are successfully prevented.

Draft link to change route type:
<img width="802" alt="Screenshot 2022-04-11 at 16 57 04" src="https://user-images.githubusercontent.com/2204224/162781785-8922d538-4b64-4b0e-8ea6-4227e19ec9fc.png">

Summary card completed checkboxes:
<img width="1134" alt="Screenshot 2022-04-11 at 16 57 20" src="https://user-images.githubusercontent.com/2204224/162781837-557e83ad-49d1-408a-99b1-6f463c91baec.png">

In this apply draft, trying to open the first two sections fails. Since they're 'completed' I would expect to be able to visit a confirmation page for them:
<img width="758" alt="Screenshot 2022-04-11 at 16 58 57" src="https://user-images.githubusercontent.com/2204224/162782101-e90c2f67-eb59-4735-8553-2fd10030298c.png">

In the check record page, I'm still shown a button to register the draft:
<img width="1157" alt="Screenshot 2022-04-11 at 16 59 46" src="https://user-images.githubusercontent.com/2204224/162782174-cb9f2f92-1e1d-492d-a2e6-77b6140b08c4.png">

2022-04-11 16:07 UTC, edwardhorsford commented
It looks like this read only user still has access to the admin section and can modify users?

At the least, I think they shouldn't be able to touch *anything* in the admin section. But probably we should prevent them seeing the section at all. I imagine they're set up as admins with special permissions. But perhaps it's better to think of them as special users who can view all, but are read only - and are not admins.

2022-04-14 08:58 UTC, richardpattinson commented
> Looking good!
> 
> There are a few places in the UI where we still offer to let edits happen - though the actions themselves are successfully prevented.
> 
> Draft link to change route type: <img alt="Screenshot 2022-04-11 at 16 57 04" width="802" src="https://user-images.githubusercontent.com/2204224/162781785-8922d538-4b64-4b0e-8ea6-4227e19ec9fc.png">
> 
> Summary card completed checkboxes: <img alt="Screenshot 2022-04-11 at 16 57 20" width="1134" src="https://user-images.githubusercontent.com/2204224/162781837-557e83ad-49d1-408a-99b1-6f463c91baec.png">
> 
> In this apply draft, trying to open the first two sections fails. Since they're 'completed' I would expect to be able to visit a confirmation page for them: <img alt="Screenshot 2022-04-11 at 16 58 57" width="758" src="https://user-images.githubusercontent.com/2204224/162782101-e90c2f67-eb59-4735-8553-2fd10030298c.png">
> 
> In the check record page, I'm still shown a button to register the draft: <img alt="Screenshot 2022-04-11 at 16 59 46" width="1157" src="https://user-images.githubusercontent.com/2204224/162782174-cb9f2f92-1e1d-492d-a2e6-77b6140b08c4.png">

I think this would be best as a seperate PR (theres a fair amount here and its a seperate responsibility to making a read only user). Definitely important to get done though.

2022-04-14 09:07 UTC, edwardhorsford approved these changes
Approving as we've agreed the remaining items will form part of a new ticket.

2022-04-14 09:07 UTC, merged