4039 dttp religious education trainees have been incorrectly mapped to philosophy
DFE-Digital/register-trainee-teachers pull request #2292
Opened 2022-04-27 12:51 UTC by richardpattinson

### Context

The ID for philosophy in Dttp::Codesets::CourseSubjects was set to be the same as that of religious education. This means that all religious education courses were being set to philosophy instead. This new service will run through each trainee with a philosophy subject specialism and check the original dttp placement assignment for the true subject specialism and will set the subject accordingly.

### Changes proposed in this pull request

Migration that runs the new service

### Guidance to review

Run the service, check the tests.

2022-04-27 12:51 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [DTTP: Religious education trainees have been incorrectly mapped to philosophy](https://trello.com/c/xg2fz1g9/4039-dttp-religious-education-trainees-have-been-incorrectly-mapped-to-philosophy)

2022-04-27 13:10 UTC, edwardhorsford commented on app/services/fix_trainees_with_incorrectly_assigned_philosophy_specialisms.rb
> +      if trainee.dttp_trainee.latest_placement_assignment.response["_dfe_ittsubject1id_value"] == RELIGIOUS_EDUCATION_DTTP_ID
I think `RELIGIOUS_EDUCATION_DTTP_ID` is misnamed - could it point to the actual code or else `RELIGIOUS_STUDIES_DTTP_ID`?

2022-05-06 06:47 UTC, gpeng requested changes

2022-05-06 06:47 UTC, gpeng commented on db/data/20220425143919_fix_incorrectly_assigned_philosophy_subject_specialisms.rb
> +    trainees = Trainee.where(course_subject_one: CourseSubjects::PHILOSOPHY).or(Trainee.where(course_subject_two: CourseSubjects::PHILOSOPHY)).or(Trainee.where(course_subject_three: CourseSubjects::P
Can we split this line?

2022-05-06 06:47 UTC, gpeng commented on db/data/20220425143919_fix_incorrectly_assigned_philosophy_subject_specialisms.rb
> +      if trainee.dttp_trainee.latest_placement_assignment.response["_dfe_ittsubject1id_value"] == RELIGIOUS_EDUCATION_DTTP_ID
I don't think this is defined `RELIGIOUS_EDUCATION_DTTP_ID`. As per @edwardhorsford 's comment it should reference the codeset RELIGIOUS_STUDIES entity id shouldn't it?

2022-05-09 13:02 UTC, gpeng approved these changes

2022-05-11 09:18 UTC, merged