4048 fix start year export
DFE-Digital/register-trainee-teachers pull request #2313
Opened 2022-05-05 08:34 UTC by richardpattinson

### Context

Fix issue where academic year is always showing up as 'nil'. Have it correctly list academic year. Change the name of academic year to start year.

### Guidance to review

Pull down export check its working.

2022-05-05 08:35 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [April HESA updates showing blank AY field?](https://trello.com/c/OKsjqZhQ/4048-april-hesa-updates-showing-blank-ay-field)

2022-05-05 09:05 UTC, gpeng requested changes

2022-05-05 09:05 UTC, gpeng commented on db/data/20220425143919_fix_incorrectly_assigned_philosophy_subject_specialisms.rb
> +class FixIncorrectlyAssignedPhilosophySubjectSpecialisms < ActiveRecord::Migration[6.1]
This isn't meant to be in this PR

2022-05-05 09:05 UTC, gpeng commented on app/services/exports/trainee_search_data.rb
> +    def start_year(trainee)
I don't this logic should be in here. Might be better on the trainee for now. Trainee also has `academic_cycle` which  already gives you this.

2022-05-06 10:30 UTC, AbigailMcP approved these changes

2022-05-06 14:13 UTC, gpeng approved these changes

2022-05-06 14:13 UTC, merged