[4246] funding csv exports
DFE-Digital/register-trainee-teachers pull request #2436
Opened 2022-06-16 13:49 UTC by richardpattinson

### Context

Fix small issues with the csv exports: 

* the filenames should match the prototype e.g.
  * west-park-primary-school-payment-schedule-2021-to-2022.csv
  * west-park-primary-school-trainee-summary-2021-to-2022.csv
* the lead school trainee summary shouldn't include the 'lead school' column
* the vulnerable character escaping is rendering `'` characters into the CSV that are visible to the user

2022-06-16 13:49 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] Funding CSV exports](https://trello.com/c/1Nrpzf2W/4246-m-funding-csv-exports)

2022-06-17 13:39 UTC, gpeng requested changes

2022-06-17 13:39 UTC, gpeng commented on app/helpers/exports_helper.rb
> +    value.start_with?(*VULNERABLE_CHARACTERS) ? "'#{value}" : value
This is still rendering the `'` in the CSV
<img width="352" alt="Screenshot 2022-06-17 at 14 38 15" src="https://user-images.githubusercontent.com/5216/174309583-43c565fa-0c50-4d6d-bedd-5c38cd04bb7e.png">

2022-06-17 15:37 UTC, gpeng requested changes

2022-06-17 15:37 UTC, gpeng commented on app/services/exports/funding_schedule_data.rb
> +      Time.zone.now.strftime("%m").to_i > 7 ? AcademicCycle.current.start_year.to_i : AcademicCycle.current.end_year.to_i
I don't think we can assume this as we'll likely be showing historic years in the future. We need to get these from the payment schedule. The years are annoyingly on the amounts so we'll need to get the min and max from those. Possibly put that as a method on PaymentSchedule?

2022-06-20 12:16 UTC, AbigailMcP approved these changes

2022-06-20 12:19 UTC, gpeng approved these changes

2022-06-20 12:19 UTC, merged