[4253] Add filters for start and end academic cycle
DFE-Digital/register-trainee-teachers pull request #2441
Opened 2022-06-20 09:53 UTC by jhenderson

### Context
https://trello.com/c/SsCIMyPQ/4253-m-add-filters-for-start-and-end-academic-cycle

### Changes proposed in this pull request
- Extend code that handles the "Start year" filter to handle "End year" values

### Guidance to review
<img width="312" alt="Screenshot 2022-06-20 at 10 49 18" src="https://user-images.githubusercontent.com/28728/174575541-313d7c17-04df-449b-a4b3-49e93d6e29b2.png">

### Important business
- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2022-06-20 15:18 UTC, jhenderson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] Add filters for start and end academic cycle](https://trello.com/c/SsCIMyPQ/4253-m-add-filters-for-start-and-end-academic-cycle)

2022-06-22 14:27 UTC, AbigailMcP requested changes

2022-06-23 09:53 UTC, edwardhorsford commented on app/services/trainees/filter.rb
> +      academic_cycle_scope = AcademicCycle.for_year(end_year).trainees_ending
I'd be happy to use the four digit year in the query string, but we'd then need to map that to the longer string form for the selected filters.

2022-06-23 09:57 UTC, jhenderson commented on app/services/trainees/filter.rb
> +      academic_cycle_scope = AcademicCycle.for_year(end_year).trainees_ending
You've raised an interesting point. The `end_year` is really expecting the string "2022 to 2023" and not just `2022`. Maybe the term `end_year` is misleading from the backend perspective. @edwardhorsford thinks we should keep the string "2022 to 2023" from a UI perspective, not so fussed about the URL param. I also think we keep the value "2022 to 2023". However, it sounds like the backend needs to make more sense, so I'll address that.

2022-06-23 10:07 UTC, AbigailMcP commented on app/services/trainees/filter.rb
> +      academic_cycle_scope = AcademicCycle.for_year(end_year).trainees_ending
happy with that!

2022-06-24 13:36 UTC, AbigailMcP commented
> @jhenderson can you confirm how we choose which years to show? Is it using start and end years that are available based on the trainees the provider has?

I'm still not sure about this, it looks like both the start and end year filters show the same years, based on whether there are trainees _starting_ in that year.

2022-06-28 09:12 UTC, edwardhorsford approved these changes

2022-06-28 11:13 UTC, jhenderson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Seeded records use unrealistic dates](https://trello.com/c/8YggmiFn/4293-seeded-records-use-unrealistic-dates)

2022-06-30 14:22 UTC, merged