[4700] - delete a user
DFE-Digital/register-trainee-teachers pull request #2750
Opened 2022-09-21 18:14 UTC by d-a-v-e

### Context

Support and operations should be able to delete / remove a user from within the support ui.

### Changes proposed in this pull request

* A link is shown on the user page to 'Delete user'
* Pressing the link takes the support user to a confirmation page
* After confirming, the user is deleted.
* The support user is redirected to the users index with a success flash message.

### Notes

This does not delete the user, only discards (to maintain timeline properties)

2022-09-21 19:45 UTC, markhallen approved these changes
LGTM

2022-09-22 10:42 UTC, edwardhorsford requested changes
There are some issues with this page:
<img width="1063" alt="Screenshot 2022-09-22 at 11 37 26" src="https://user-images.githubusercontent.com/2204224/191726117-0f6dc4f0-89a2-4c6b-bbce-4c64455c06ca.png">

Issues:
* Page layout is off - esp the back link - can we look at existing delete pages?
* Need correct apostrophes rather than primes
* Cancel link is too small - check how other cancel links are done

I got this weird case when deleting a user:
<img width="1111" alt="Screenshot 2022-09-22 at 11 38 52" src="https://user-images.githubusercontent.com/2204224/191726385-c0693ea1-f7bf-4dc7-8bec-b74e37118518.png">

I *think* this is because I deleted an admin account. I think this is a requirement we missed - we should not let support users delete admin accounts (I reckon only devs should be able to create or delete admin accounts).

2022-09-22 13:47 UTC, claire-hughez commented
@edwardhorsford do you have any examples of the back links or cancel text that Dave can steal please?

Also, I can't view this now as Ed deleted the account to view things on system admin.... hahahhaha

2022-09-22 14:00 UTC, d-a-v-e commented
> 

i've got the backlink sorted - it's wrapped in a breadcrumb component throughout the rest of the app

2022-09-22 14:22 UTC, d-a-v-e commented
@edwardhorsford think all wrinkles are addressed. Can no longer delete Admins as well:


https://user-images.githubusercontent.com/6339025/191772493-2ffb0a78-455c-4320-97c8-2ebab8bdcb13.mov

2022-09-22 15:14 UTC, claire-hughez commented
I still can't log in now to check this PR haha. How can we recreate the account here?

2022-09-22 16:52 UTC, edwardhorsford requested changes

2022-09-22 16:52 UTC, edwardhorsford commented on app/views/system_admin/users/delete.html.erb
> +    <%= govuk_button_to("Yes I'm sure - delete #{@user.name}’s account", user_path(@user), method: :delete, class: "govuk-button--warning") %>
```suggestion
    <%= govuk_button_to("Yes I’m sure – delete #{@user.name}’s account", user_path(@user), method: :delete, class: "govuk-button--warning") %>
```

2022-09-22 16:52 UTC, edwardhorsford commented on app/views/system_admin/users/delete.html.erb
> +    <span class="govuk-caption-l"> <%= @user.name %> </span>
```suggestion
    <span class="govuk-caption-l"><%= @user.name %></span>
```

2022-09-22 20:59 UTC, edwardhorsford approved these changes

2022-09-23 08:28 UTC, claire-hughez commented
Looks perfect to me Dave!

2022-09-23 09:09 UTC, merged