[4631] Add hesa data mapping page
DFE-Digital/register-trainee-teachers pull request #2758
Opened 2022-09-26 16:29 UTC by richardpattinson

### Context

Create new page of content 'Check the data mapping between HESA and Register trainee teachers'

This is because we are improving and expanding the guidance pages for Register. 

### Success
- The Guidance index page has a link to the new page. The link should be called 'Check the data mapping between HESA and Register trainee teachers' - Guidance index page in the prototype: https://register-prototype.herokuapp.com/guidance
- The Homepage has a link to the new page. The link should be called 'Check the data mapping between HESA and Register trainee teachers' - Homepage in the prototype: https://register-prototype.herokuapp.com/home
- New page is created with URL: register-trainee-teachers.service.gov.uk/guidance/hesa-register-data-mapping
- It has the content from the prototype: https://register-prototype.herokuapp.com/guidance/hesa-register-data-mapping/trainee-progress
- It has a backlink to take them back to 'How to use this service': register-trainee-teachers.service.gov.uk/guidance

### Changes proposed in this pull request

### Guidance to review

Compare new pages (guidance/hesa-register-data-mapping/trainee-progress)  to prototype:https://register-prototype.herokuapp.com/guidance/hesa-register-data-mapping/trainee-progress

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2022-09-26 16:34 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create page for HEIs to check how data maps from HESA to Register](https://trello.com/c/30XKIKxY/4631-create-page-for-heis-to-check-how-data-maps-from-hesa-to-register)

2022-09-28 13:28 UTC, claire-hughez commented
When I click any of the links for 'How to use this service' it doesn't work in this deployment. It's working fine in prod currently. Any idea why?

2022-09-28 13:31 UTC, claire-hughez commented
It is also missing this part of the success criteria:

'The Homepage has a link to the new page. The link should be called 'Check the data mapping between HESA and Register trainee teachers' - Homepage in the prototype: https://register-prototype.herokuapp.com/home'

2022-09-28 14:38 UTC, edwardhorsford requested changes
looking good! just a few small changes

2022-09-28 14:38 UTC, edwardhorsford commented on app/views/guidance/_database_only.html.erb
> +</p>
These paragraphs are duplicates of the main page ones - the prototype has different content.

2022-09-28 14:38 UTC, edwardhorsford commented on app/views/guidance/hesa_register_data_mapping.html.erb
> +    <h1 class="govuk-heading-l govuk-!-margin-bottom-9">Check the data mapping between HESA and Register trainee teachers</h1>
```suggestion
    <h1 class="govuk-heading-l">Check the data mapping between HESA and Register trainee teachers</h1>
```

2022-09-28 14:38 UTC, edwardhorsford commented on app/views/guidance/hesa_register_data_mapping.html.erb
> +<%= render PageTitle::View.new(text: "Hesa register data mapping") %>
```suggestion
<%= render PageTitle::View.new(text: "Check the data mapping between HESA and Register trainee teachers") %>
```

Ideally the title would include the partial for the tab. Eg `Check the data mapping between HESA and Register trainee teachers - Trainee progress`

2022-09-28 15:42 UTC, MaeveRoseveare reviewed
Looks good, just left some changes to content that needs updating!

2022-09-28 15:42 UTC, MaeveRoseveare commented on app/views/guidance/_database_only.html.erb
> +  Use the table to check how data maps between HESA and Register trainee teachers (Register).
```suggestion
  These HESA fields are used for analysis and map to Register’s database, so you will not see them in the Register service or the CSV export.
```

2022-09-28 15:42 UTC, MaeveRoseveare commented on app/views/guidance/_database_only.html.erb
> +  Where possible, these tables follow the same order as the CSV export and a trainee’s record in Register.
```suggestion
  For school placements (HESA field PLMNTSCH), although we collect and use this data, you cannot view it in the service or the CSV yet.
```

2022-09-28 16:23 UTC, edwardhorsford commented
A minor thing: we should always use hyphens for separators in urls, not underscores.

2022-09-29 09:20 UTC, edwardhorsford approved these changes

2022-09-29 12:02 UTC, merged