[611] Retrieve TRN
DFE-Digital/register-trainee-teachers pull request #280
Opened 2020-12-11 14:03 UTC by jhenderson

### Context
https://trello.com/c/wr0DhiCW/611-l-retrieve-trn

### Changes proposed in this pull request
TBC

### Guidance to review
TBC

2020-12-14 12:29 UTC, jhenderson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[L] Retrieve TRN](https://trello.com/c/wr0DhiCW/611-l-retrieve-trn)

2020-12-14 12:48 UTC, gpeng requested changes

2020-12-14 12:48 UTC, gpeng commented on app/services/dttp/retrieve_trn.rb
> +      RetrieveTrnJob.set(wait: POLL_INTERVAL).perform_later(trainee.id) if continue_polling?
I think we're mixing concerns here. If we do it like this the service has to be aware that it is being called by a job. I think the service should just return either the TRN or nil and the calling job can then decide to update the trainee or queue another job. This service wouldn't need to know about the trainee particularly either could just take a dttp_id argument and return a TRN or not.

2020-12-15 12:30 UTC, gpeng approved these changes
This looks good. We'll probably need to tweak the polling periods, maybe move those into settings but we can do that when we need to 👍

2020-12-15 13:44 UTC, merged