[4737] Add autocomplete to search for users in the support interface
DFE-Digital/register-trainee-teachers pull request #2818
Opened 2022-10-10 17:15 UTC by richardpattinson

### Context
To make it easy to find users in support, we should add an autocomplete that lets admins search for users.

This autocomplete should route to the users show page for the selected user. 

![image](https://user-images.githubusercontent.com/44261976/194920010-51f21cc5-3cee-4015-8926-c13e9b588930.png)

### Changes proposed in this pull request

* An autocomplete is added to the users index.
* Admins can search by various attributes (name, email, provider name)
* On confirm, the admin is redirected to the user (no form submission needed)
* Autocomplete styled like screenshot

### Guidance to review

Login and head to system-admin/users and try out the new autocompete! (you need to press enter once you've selected your user)

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2022-10-10 17:47 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Potential bug with Apply disability mapping](https://trello.com/c/SXDbeEFn/4733-potential-bug-with-apply-disability-mapping)

2022-10-10 17:48 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] Support: add autocomplete to search for users](https://trello.com/c/PbsihW8T/4737-m-support-add-autocomplete-to-search-for-users)

2022-10-11 09:04 UTC, d-a-v-e requested changes
Looks great, and works great, just some suggestions for moving some of those methods out of the user model.

2022-10-11 09:52 UTC, edwardhorsford requested changes
The usage of the search is a bit unclear - you pick an item and nothing happens, and there's no submit button.

Can we please do one of the following:

* Add a search button to the right of the autocomplete
* Have the form self submit after picking the item (this is what I did in the prototype and would be preferred)

2022-10-11 09:52 UTC, edwardhorsford commented on app/views/system_admin/users/index.html.erb
> +          html_attributes: { id: "search-box" },
Indentation

2022-10-11 09:53 UTC, AbigailMcP reviewed
When I search for a user and press enter (or press the result) it doesn't navigate me anywhere, I just stay on the users index page.

2022-10-11 09:56 UTC, AbigailMcP reviewed
Please can we deploy this to test on productiondata - production has 1200 users whereas the review app only has 7. We should test what it's like loading >1000 entries into the select component.

2022-10-11 12:50 UTC, richardpattinson commented
> Please can we deploy this to test on productiondata - production has 1200 users whereas the review app only has 7. We should test what it's like loading >1000 entries into the select component.

Deploying now. Ill have a look and see if it can handle all the users.

2022-10-11 12:51 UTC, richardpattinson commented
> When I search for a user and press enter (or press the result) it doesn't navigate me anywhere, I just stay on the users index page.
> 
> Edit: Ed just beat me to this 😂

I think one has to press the option, ensure the checkbox is selected and press enter. At least that behaviour is working on my end

2022-10-13 10:26 UTC, richardpattinson commented
> Please can we deploy this to test on productiondata - production has 1200 users whereas the review app only has 7. We should test what it's like loading >1000 entries into the select component.

Yesterday when i tried the productiondata set it was really slow. Ive tried it again today and its working surprisingly well - i suspect my internet connection was at fault yesterday. I think this is ready for re review.

2022-10-13 11:08 UTC, edwardhorsford commented
Checking again, there's a few issues:

* Some orgs get repeated:
<img width="496" alt="Screenshot 2022-10-13 at 12 05 33" src="https://user-images.githubusercontent.com/2204224/195581148-dd441eb9-723f-4bc8-abec-31cf951f3349.png">
* Some users appear twice in the list (can send details privately)
* Hints aren't styled like hints
* Button not inline.

2022-10-13 11:09 UTC, markhallen commented on app/forms/user_search_form.rb
> +    @users = User.send(scope).includes(:providers, :lead_schools)
We should cache this

2022-10-13 11:12 UTC, edwardhorsford commented
I get this if submitting without a valid user.

<img width="1089" alt="Screenshot 2022-10-13 at 12 11 35" src="https://user-images.githubusercontent.com/2204224/195581716-ddc61790-16f3-4b3d-ac37-005a14bdaea9.png">

2023-01-12 10:31 UTC, claire-hughez commented
I think this already got done separately, so do we need to just get rid of this PR?

2023-01-13 16:08 UTC, closed without merging