4669 allow users to change routes and courses on registered trainees
DFE-Digital/register-trainee-teachers pull request #2823
Opened 2022-10-11 18:52 UTC by HettieS

### Context

### Changes proposed in this pull request

### Guidance to review

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2022-10-12 10:27 UTC, HettieS commented on app/forms/publish_course_details_form.rb
> +    clear_funding_information if clear_funding_information?
I've added this check here as it is used in CourseDetailsForm and ConfirmCourseForm and seems it was missing here - I don't think we were clearing funding properly for publish courses potentially

2022-10-14 15:08 UTC, jhenderson requested changes
Great work @HettieS. A few small suggestions.

2022-11-23 14:55 UTC, HettieS commented on app/forms/publish_course_details_form.rb
> +    clear_funding_information if clear_funding_information?
I've removed this and added it to another branch here we should do the fix for this.

2022-11-23 14:55 UTC, HettieS commented
> I've just seen a bug where we clear funding when the route/subject changes but we then don't surface the correct funding option - we give them a page relating to the previous course. Not sure if existing bug or created in this PR yet. ![Screenshot 2022-10-12 at 11 41 20](https://user-images.githubusercontent.com/43522239/195322250-2a3eb53f-c3c3-4af0-991a-948f32ea0aaf.png) ![Screenshot 2022-10-12 at 11 41 28](https://user-images.githubusercontent.com/43522239/195322261-ed51fd7a-cd70-4c26-80a0-413e6ca3bbbc.png)

note: I've raised this as a separate bug ticket and will not fix on this PR

2022-12-01 12:20 UTC, jhenderson approved these changes
Looking good. Some minor suggestions.

2022-12-01 12:20 UTC, jhenderson commented on app/helpers/publish_courses_helper.rb
> +  def courses_fieldset_text_for(_trainee)
You can get rid of the `_trainee` argument. You'll have to update the method here also: http://github.com/DFE-Digital/register-trainee-teachers/blob/f2f6f3a83e5be4b366629cd2ca09a868d2bec962/app/views/trainees/publish_course_details/edit.html.erb#L29-L29

2022-12-01 12:20 UTC, jhenderson commented on app/views/trainees/publish_course_details/edit.html.erb
> +              hint: { text: "#{course.summary}" },
```suggestion
              hint: { text: course.summary },
```

2022-12-08 12:16 UTC, HettieS commented
Existing bugs in the publish course details flow/clearing the funding should now be fixed on this PR.

2022-12-09 10:30 UTC, HettieS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Production: changing from one publish course to another publish course does not update the trainee's course details](https://trello.com/c/GbgVm6Lb/5050-production-changing-from-one-publish-course-to-another-publish-course-does-not-update-the-trainees-course-details)

2022-12-09 10:32 UTC, HettieS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Funding method not being cleared for publish course changes](https://trello.com/c/fHrmVh7z/5019-funding-method-not-being-cleared-for-publish-course-changes)

2022-12-09 12:23 UTC, edwardhorsford approved these changes
Have walked through this in detail with @HettieS. Looking great!

We've found a number of bugs along the way - but believe they are all preexisting issues so we'll raise separately.

🎉

2022-12-09 14:36 UTC, markhallen approved these changes
LGTM

2022-12-12 10:20 UTC, merged