[4907] Add HESA Cyprus codes
DFE-Digital/register-trainee-teachers pull request #2916
Opened 2022-11-14 15:06 UTC by HettieS

### Context

Trello: https://trello.com/c/edXQJ5f4/4907-itt-register-portal-data-check-for-c22053

Cypriot nationality did not map for some HESA trainees because we did not hold the HESA codes XA and XB in Register. Apply also does not currently hold them in their nationalities mapping, but does in their countries and territories: https://github.com/DFE-Digital/apply-for-teacher-training/pull/6584

I spoke with Duncan and we agreed that Register should accept the valid HESA nationality codes for Cyprus, and allow them to be added to our seeded nationalities. They will also display in our nationality autocomplete. We should hide the existing generic 'cypriot' option from the autocomplete so that providers must choose between EU or non-EU.

We do not need to alter any existing Cypriot trainee nationalisations as we have no real way of knowing who is EU or non-EU.

**One issue with this new implementation - because I have removed 'cypriot' from the loaded nationalities and therefore the autocomplete, if an existing trainee with 'Cypriot' as nationality has their personal details edited, the user will be told that the nationality is invalid, and they'll need to pick between EU and non-EU variants in order to save the form.**

I'm going to have a look at the HESA data and see if I can see them sending us any invalid codes (CY or XC) so we can contact HESA about that. Will do this in a separate ticket.

### Changes proposed in this pull request

* Add new cyprus options to `ApplyApi::CodeSets::Nationalities::MAPPING`
* Add data migration to add the two new Cypriot nationalities
* Add cyprus options to `DTTP::CodeSets::Nationalities:MAPPING` for the seeds
* Move some logic from controller to model and create `default` and `other` scope
* Use new scopes to exclude 'cyprus' so it does not display in autocomplete

### Guidance to review

* Check we are happy with the consequences for existing cypriot trainees

Prod review:
* Edit a draft and registered trainees' nationality to be cypriot EU and cypriot non-EU - observe it selects and saves correctly
* Observe the generic 'cypriot' option does not appear in the autocomplete

### Important business

- [ ] ~~Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?~~
- [ ] ~~Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~~

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2022-11-15 10:37 UTC, HettieS commented
![](https://github.trello.services/images/mini-trello-icon.png) [ITT Register Portal Data Check for C22053](https://trello.com/c/edXQJ5f4/4907-itt-register-portal-data-check-for-c22053)

2022-11-16 09:48 UTC, d-a-v-e requested changes
I think this is missing an addition to the `nationalities` table

Looking at `app/views/trainees/personal_details/edit.html.erb:63` I can see all of the nationality forms build their list from `@other_nationalities` which is populated in `app/controllers/trainees/personal_details_controller.rb:53.

We probably want to update `app/lib/dttp/code_sets/nationalities.rb` with the non-eu Cyprus  region/country and then re-seed in each environment to get the new values in.

2022-11-16 09:51 UTC, d-a-v-e commented
@HettieS there's two "inactive" mappings in that file which I believe you just move into MAPPING

`app/lib/dttp/code_sets/nationalities.rb:277`
`app/lib/dttp/code_sets/nationalities.rb:278`

2022-11-17 17:09 UTC, HettieS commented on app/lib/dttp/code_sets/nationalities.rb
>          "Cyprus not otherwise specified" => { entity_id: "037f640e-5c62-e711-80d1-005056ac45bb" },
Cyprus not otherwise specified is currently an invalid HESA option (XC)

2022-11-17 17:09 UTC, HettieS commented on app/lib/dttp/code_sets/nationalities.rb
> +        "cypriot (european union)" => { entity_id: "017f640e-5c62-e711-80d1-005056ac45bb" },
wasn't too sure what to use for the entity_id, or if it is even still relevant

2022-11-25 13:46 UTC, d-a-v-e approved these changes
nice work! G2G :shipit:

2022-11-29 10:21 UTC, edwardhorsford approved these changes

2022-11-29 13:37 UTC, merged