[4995] Add iQTS route
DFE-Digital/register-trainee-teachers pull request #2945
Opened 2022-11-28 12:21 UTC by AbigailMcP

### Context

### Changes proposed in this pull request

- Add new iQTS enum option to training_routes on trainee
- Add new feature flag to ensure this is off in prod (enabled in review, dev and QA)
- Add new `requires_funding?` method to `TrainingRouteManger` which returns true for all routes except for iQTS
- Use `requires_funding?` method to hide funding sections and prevent funding validation for iQTS trainees.

### Guidance to review

### Important business

- [ ] ~Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?~
- [ ] ~Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2022-11-28 12:22 UTC, AbigailMcP commented on app/helpers/training_routes_helper.rb
> +module TrainingRoutesHelper
Refactor - taking logic out of view now it's getting a bit more complicated re different hints.

2022-11-28 12:23 UTC, AbigailMcP commented on app/views/trainees/training_routes/_form_fields.html.erb
> -          hint: { text: (TRAINING_ROUTE_ENUMS[training_route].starts_with?("provider_led") && t(".provider_led_hint")) },
Moved into helper to take this logic out of the view now we have multiple hints for multiple routes.

2022-12-02 10:35 UTC, AbigailMcP commented
![](https://github.trello.services/images/mini-trello-icon.png) [[L] Add support for iQTS - add new route](https://trello.com/c/mMwhWwkT/5043-l-add-support-for-iqts-add-new-route)

2022-12-05 21:10 UTC, markhallen approved these changes
LGTM

2022-12-07 17:35 UTC, edwardhorsford requested changes
I've had a look with @johndoates - looking good!

* Can the route be alphabetical in the route list
* In the route switcher in the draft, we need `(iQTS)` to be correctly cased:
<img width="609" alt="Screenshot 2022-12-07 at 17 07 01" src="https://user-images.githubusercontent.com/2204224/206244642-fd007bbf-08ac-49ef-bd5a-c7511c9694c0.png">

* Hint for autocomplete needs a full stop.
* Needs a validation message for autocomplete - `Enter the country or territory the trainee is studying in`
* Needs a validation message when country not recognised `Enter the country or territory the trainee is studying in`
* @claire-hughez do you think we should error if they pick `United Kingdom`. Alternately we could remove it from the list. We might want to check with the iQTS team.
* Please make the autocomplete narrower.
* Filters: please put route alphabetical in list
* Seeds for iQTS trainees need a training country

2022-12-08 12:40 UTC, AbigailMcP commented
> * Can the route be alphabetical in the route list

done

> * In the route switcher in the draft, we need `(iQTS)` to be correctly cased:
> 
> <img alt="Screenshot 2022-12-07 at 17 07 01" width="609" src="https://user-images.githubusercontent.com/2204224/206244642-fd007bbf-08ac-49ef-bd5a-c7511c9694c0.png">

done, also fixed for HPITT route (which was rendering as "hpitt")

> * Hint for autocomplete needs a full stop.

done

> * Needs a validation message for autocomplete - `Enter the country or territory the trainee is studying in`

done

> * Needs a validation message when country not recognised `Enter the country or territory the trainee is studying in`
> * @claire-hughez do you think we should error if they pick `United Kingdom`. Alternately we could remove it from the list. We might want to check with the iQTS team.

waiting on iQTS team response

> * Please make the autocomplete narrower.

done

> * Filters: please put route alphabetical in list

done

> * Seeds for iQTS trainees need a training country

TBC

2022-12-08 16:23 UTC, edwardhorsford approved these changes
Looking great!

2022-12-16 11:24 UTC, merged