[5145] - Make raw HESA collection data accessible to System Admins
DFE-Digital/register-trainee-teachers pull request #3059
Opened 2023-01-23 15:06 UTC by d-a-v-e

### Context

We want to make raw HESA collection data accessible from trainee records for admin users.

Admins often need to look at a trainee record, and compare that with what was submitted to HESA. Currently that can be done by looking up the slug in Blazer - but this is slow. It would be easier if the raw collection data was accessible from the record. 

[Link to page in prototype](https://register-prototype.herokuapp.com/record/08283e35-45f4-47dc-b8a7-0ddd305e31c1/admin)

This was [added to the prototype in this pr](https://github.com/DFE-Digital/register-trainee-teachers-prototype/pull/611). You can try in the prototype by setting the user type to admin and viewing a record.

It's expected we may add more features / rows / metadata to this admin tab in the future.

### Changes proposed in this pull request

Adds HesaStudentSummary view component and corresponding page visible only to admins

### Guidance to review

* real data is needed to test retrieval of HESA data so please make use of the productiondata deploy (or use a local copy)

### Important business

- [ ] ~Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?~
- [ ] ~Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~
- [ ] ~Do we need to send any updates to DQT as part of the work in this PR?~
- [ ] ~Does this PR need an ADR?~

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2023-01-23 16:24 UTC, edwardhorsford requested changes
Looking good @d-a-v-e !

Some comments / suggestions:

* ~Reckon the order of rows should be chronological - so c21 then c22~
* Only show a collection row if we have data for it. So if we only have C22, don't show a row for C21 (I think register currently only ever has data for a single collection for a trainee - but hopefully that will change soon)
* I think the headings should likely be h3s? - the summary card itself has an h2, so this should be the next level down
* Ideally the headings would be correctly pluralised based on the contents. But if you don’t fancy bothering, just use the plural form, so Degrees , not Degree(s)
* For non hesa trainees, don’t render the hesa summary card at all

What date is shown in the heading of the details? I’d expect it to be the last modified date or last time we received new data from HESA. But 15 November 2022 is well before the hesa updated at date.

2023-01-23 16:25 UTC, edwardhorsford commented on app/views/trainees/admins/show.html.erb
> +         <%= render HesaStudentSummary::View.new(trainee:, collection: "C21053") %>
Feels like these should be dynamic based on what data we have?

2023-01-23 16:42 UTC, edwardhorsford commented
Disregard the chronological request - @claire-hughez thinks the newest should be first.

2023-01-23 16:59 UTC, claire-hughez commented
> Disregard the chronological request - @claire-hughez thinks the newest should be first.

Because I'm a tyrant....

Nah, because I think for Support (and for us potentially?), it will make more sense for the most recent HESA collection to be first, as that's what will be most relevant for the actual trainee record they see.

2023-01-23 20:56 UTC, d-a-v-e commented
> * Only show a collection row if we have data for it. So if we only have C22, don't show a row for C21 (I think register currently only ever has data for a single collection for a trainee - but hopefully that will change soon)

done

> * I think the headings should likely be h3s? - the summary card itself has an h2, so this should be the next level down

done

> * Ideally the headings would be correctly pluralised based on the contents. But if you don’t fancy bothering, just use the plural form, so Degrees , not Degree(s)

done

> * For non hesa trainees, don’t render the hesa summary card at all

and done!

2023-01-24 11:34 UTC, HettieS commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Admins: Make raw HESA collection data accessible from trainee records](https://trello.com/c/IaPTEiiq/5145-s-admins-make-raw-hesa-collection-data-accessible-from-trainee-records)

2023-01-24 12:01 UTC, HettieS reviewed
Looks good, I've left a few questions. I'll give it a review in prod data env and will approve if all looks good :)

2023-01-24 12:06 UTC, HettieS commented on app/controllers/application_controller_dev.rb
> +      user = User.where(system_admin: false).first
I'm not sure what this file is doing?

2023-01-24 12:09 UTC, d-a-v-e commented on app/components/hesa_student_summary/view.rb
> +      return if degrees.empty?
only as I'm expecting an array either way

2023-01-24 12:10 UTC, d-a-v-e commented on app/components/tab_navigation/view.rb
> +      @items = items&.compact
probably not, but I wasn't sure if this ever gets instantiated without any items, so just a precaution.

2023-01-24 12:14 UTC, d-a-v-e commented on app/components/hesa_student_summary/view.rb
> +    # 4 December 2022 at 1:07pm
I've left this in as the `strftime` is a bit cryptic

2023-01-24 12:16 UTC, d-a-v-e commented on app/views/trainees/admins/show.html.erb
> +<% if trainee.hesa_id %>
good shout, I'll check for a record instead

2023-01-24 14:47 UTC, HettieS approved these changes

2023-01-24 16:22 UTC, merged