[5194] Link to trainees from dead job viewer
DFE-Digital/register-trainee-teachers pull request #3080
Opened 2023-01-31 09:48 UTC by richardpattinson

### Context

Link to trainees from the show page of dead job viewer.

### Changes proposed in this pull request

Add a button to link to the trainee from the dead job viewer.

### Guidance to review

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [ ] Do we need to send any updates to DQT as part of the work in this PR?
- [ ] Does this PR need an ADR?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2023-02-01 09:16 UTC, d-a-v-e requested changes
That currently will through a syntax error, try this:

```erb
<table class="govuk-table">
  <caption class="govuk-table__caption govuk-table__caption--m"><%= dead_job_service.name %></caption>
  <thead class="govuk-table__head">
    <tr class="govuk-table__row">
      <% dead_job_service.headers&.each do |header| %>
        <th scope="col" class="govuk-table__header"><%= header.to_s.humanize %></th>
      <% end %>
      <th scope="col" class="govuk-table__header"></th>
    </tr>
  </thead>
  <tbody class="govuk-table__body">
    <% dead_job_service.rows&.each do |row| %>
      <tr class="govuk-table__row">
        <% row.each do |data| %>
          <td class="govuk-table__cell"><%= data[-1] %></td>
        <% end %>
        <td class="govuk-table__cell">
          <%= render GovukButtonLinkTo::View.new(
            body: "View",
            url: trainee_path(Trainee.find(row[:register_id])),
            class_option: "govuk-!-margin-bottom-0",
          ) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
```

2023-02-02 16:04 UTC, jhenderson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dead Job Viewer: Link to trainees from Show page](https://trello.com/c/UmeGCx6O/5194-dead-job-viewer-link-to-trainees-from-show-page)

2023-02-03 08:56 UTC, d-a-v-e commented on app/views/system_admin/dead_jobs/index.html.erb
> +                id: "view_#{service.name.gsub(" ", "_").downcase}",
each service has a method that looks like it does this just call `service.identifier`

2023-02-03 08:58 UTC, d-a-v-e commented on app/views/system_admin/dead_jobs/index.html.erb
> +                id: "view_#{service.name.gsub(" ", "_").downcase}",
although you'll need to move the method out of private (in `dead_jobs/base.rb`)

2023-02-03 09:08 UTC, d-a-v-e approved these changes
make use of the `service.identifier` method then this looks G2G 👍

2023-02-07 09:59 UTC, merged