[5212] - display all applicable years when changing course
DFE-Digital/register-trainee-teachers pull request #3089
Opened 2023-02-02 23:15 UTC by d-a-v-e

### Context

When using the new course change flow from an existing registered trainees, it seems it suggests courses from the current academic year, rather than the academic year of the start year of the trainee.

If the trainee has an existing publish course, then it seems to correctly use that course's academic year. But if there is no pre-existing publish course, then it uses the current year when it should use the start academic year.

### Changes proposed in this pull request

Expose course years for a trainee when changing course that go back as far as either the trainees ITT start data year or their course recruitment cycle year, whichever is oldest.

2023-02-02 23:16 UTC, d-a-v-e commented
![](https://github.trello.services/images/mini-trello-icon.png) [Course change flow suggests courses from the wrong academic year](https://trello.com/c/y5wtvy6r/5212-course-change-flow-suggests-courses-from-the-wrong-academic-year)

2023-02-06 10:38 UTC, edwardhorsford commented on app/forms/course_years_form.rb
> +    ].compact.min
Can you explain what this bit is doing? the previous felt easier to read - by default (drafts) we want the form to show the default course year and the one prior - I don't think that's the same as the recruitment cycle year.

2023-02-06 10:38 UTC, edwardhorsford commented on app/forms/course_years_form.rb
>    end
It's possible for a trainee not to have an itt start date. Don't know if that's relevant here.

2023-02-06 10:38 UTC, edwardhorsford commented on app/forms/course_years_form.rb
> +  end
I'm wary of using variables mentioning `recruitment_cycle` - these frequently get confused with academic cycles and end up with an off by one error. And sometimes they are the *same* as the academic cycle (eg they are poorly labelled).

2023-02-06 10:42 UTC, edwardhorsford commented on app/forms/course_years_form.rb
> +    ].compact.min
I think in our new form, we'd want the available years to be all the years between the default course year and the "start year" - where the start year is the earlier of itt start date or the existing course year.

2023-02-06 19:21 UTC, d-a-v-e commented on app/controllers/trainees/publish_course_details_controller.rb
> +      year ||= @trainee.start_academic_cycle&.start_year
@edwardhorsford I've added start_academic_cycle start year as a possible default here

2023-02-08 12:33 UTC, HettieS reviewed
Looks good! Will approve once you're ready with the changes :)

2023-02-08 12:33 UTC, HettieS commented on app/controllers/trainees/publish_course_details_controller.rb
> +      return @year if defined?(@year)
year should never be nil

2023-02-08 12:33 UTC, HettieS commented on app/controllers/trainees/publish_course_details_controller.rb
```suggestion
return if params[:year].present?
```

2023-02-08 12:34 UTC, HettieS requested changes
see changes

2023-02-08 14:45 UTC, HettieS requested changes
looking good 👍 just one tiny comment!

2023-02-08 14:45 UTC, HettieS commented on app/models/trainee.rb
> +  def current_course
let's remove this method now that we aren't using it to avoid future confusion about what it does

2023-02-08 14:50 UTC, HettieS approved these changes

2023-02-08 15:25 UTC, merged