[5264] - Bulk recommend CSV import
DFE-Digital/register-trainee-teachers pull request #3113
Opened 2023-02-16 17:03 UTC by d-a-v-e

### Context
MVP for CSV import (see trello ticket)
### Changes proposed in this pull request
...

### Guidance to review
...

### Important business
...

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [x] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

2023-02-17 09:43 UTC, d-a-v-e commented
![](https://github.trello.services/images/mini-trello-icon.png) [[L] Bulk QTS: CSV import](https://trello.com/c/GKKWlEva/5264-l-bulk-qts-csv-import)

2023-02-22 15:51 UTC, edwardhorsford commented on app/models/bulk_update.rb
> +module BulkUpdate
In the future we may have other bulk imports of things - is that relevant?

2023-02-22 15:56 UTC, d-a-v-e commented on app/models/bulk_update.rb
> +module BulkUpdate
yeah - we've made it a bit more generic to leave space for extending the use. the new tables are prefixed with bulk_update

2023-02-24 16:05 UTC, markhallen requested changes
Looks good so far!

2023-02-27 13:59 UTC, d-a-v-e commented on db/migrate/20230216164121_create_bulk_update_recommendations_uploads.rb
> +      t.belongs_to :user, null: false, foreign_key: true
we'd end up with orphaned bulk uploads, is it better that - for now - an attempt at deleting a user with bulk uploads would throw an exception?

2023-02-28 09:32 UTC, markhallen approved these changes

2023-02-28 09:32 UTC, merged