[5352] Surface details for awarded, deferred and withdrawn trainees
DFE-Digital/register-trainee-teachers pull request #3196
Opened 2023-04-06 08:39 UTC by richardpattinson

### Context

Add details components for awarded, withdrawn and deferred trainees to the trainee record page. 

### Changes proposed in this pull request

Should be a new details component on the trainee show page for awarded, deferred and withdrawn trainees/

### Guidance to review

Good candidate to check in the browser.

2023-04-06 08:43 UTC, richardpattinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Surface withdrawal, deferral, and award summary cards on trainee record](https://trello.com/c/gBRwwptt/5352-s-surface-withdrawal-deferral-and-award-summary-cards-on-trainee-record)

2023-04-12 10:46 UTC, jhenderson commented on spec/views/trainees/show.html.erb_spec.rb
> +  context "details components" do
```suggestion
context "details components" do
  let(:trainee) { create(:trainee, state) }
  let(:current_user) { create(:user, :system_admin) }

  before { render }

  context "withdrawn trainee" do
    let(:state) { :withdrawn }

    it "renders the check withdrawn component" do
      expect(rendered).to have_text("Withdrawal details")
    end
  end

  context "deferred trainee" do
    let(:state) { :deferred }

    it "renders the check withdrawn component" do
      expect(rendered).to have_text("Deferral details")
    end
  end

  context "awarded trainee" do
    let(:state) { :awarded }

    it "renders the check withdrawn component" do
      expect(rendered).to have_text("QTS details")
    end
  end
end
```

2023-04-12 10:47 UTC, jhenderson approved these changes
Left a suggestion to refactor the spec.

2023-04-12 15:11 UTC, edwardhorsford requested changes
Other issues:
* looks like these have change links when they shouldn't - we should be using the existing change permissions.
* Possibly more worryingly, the change links actually *work* - this might be a preexisting bug?
* The status row should generally be removed from the trainee progress card where we've got this other card.
* There should be a card on recommended trainees

2023-04-18 08:43 UTC, richardpattinson commented
> Other issues:
> 
> * looks like these have change links when they shouldn't - we should be using the existing change permissions.
> * Possibly more worryingly, the change links actually _work_ - this might be a preexisting bug?
> * The status row should generally be removed from the trainee progress card where we've got this other card.
> * There should be a card on recommended trainees

These changes should be made now. What do you mean by there should be a card on reccomended trainees?

2023-04-18 10:19 UTC, edwardhorsford commented
I'm still seeing a status row.

<img width="1015" alt="Screenshot 2023-04-18 at 11 19 37" src="https://user-images.githubusercontent.com/2204224/232748071-629a5964-ba77-485b-b812-1c7f7c55f3f7.png">

2023-04-18 10:34 UTC, edwardhorsford commented
> These changes should be made now. What do you mean by there should be a card on reccomended trainees?

I mean that for recommended trainees, there should be a card (instead of a status row) just like there is one for awarded trainees

2023-04-18 10:37 UTC, edwardhorsford commented
The deferral and withdrawal cards include trainee start date, which is incorrect. There's an argument that this is a pre-existing bug as we're just reusing the cards here.

Trainee start date is conditionally asked about within both of those flows, where we don't have a trainee start date - the intention was that the confirmation page only showed it where we'd *just* asked about the start date. In most cases it should never have been visible. 

@claire-hughez try to remove as part of this card, or raise a new bug?
<img width="1008" alt="Screenshot 2023-04-18 at 11 34 54" src="https://user-images.githubusercontent.com/2204224/232751720-822b2492-5c3d-4a29-adfb-5d94f9308893.png">

2023-04-18 10:43 UTC, claire-hughez commented
@richardpattinson @markhallen @edwardhorsford 
I don't think we should release that at the very least if it causes a duplicate in the trainee start date on the record - it looks pretty glaringly wrong in that screenshot. We can create a bug ticket to solve it before this is released or solve as part of this ticket. What do ya devs think? :)

2023-04-18 10:49 UTC, edwardhorsford commented
> @richardpattinson @markhallen @edwardhorsford I don't think we should release that at the very least if it causes a duplicate in the trainee start date on the record - it looks pretty glaringly wrong in that screenshot. We can create a bug ticket to solve it before this is released or solve as part of this ticket. What do ya devs think? :)

Regardless of which we do, it would be good to fix the underlying bug - that the row is shown in the summary card regardless of the journey, rather than the minority journey where it's needed.

2023-04-19 19:50 UTC, edwardhorsford commented
I think the only remaining thing is to remove the status row for deferred, recommended, and awarded trainees.

2023-04-24 14:21 UTC, edwardhorsford commented
Something has gone wrong for pending trn trainees. I'm not sure what this QTS row is doing here.
<img width="1029" alt="Screenshot 2023-04-24 at 15 20 27" src="https://user-images.githubusercontent.com/2204224/234025128-e671c2ea-5779-4ec8-b752-cf10f346de81.png">

Here's what it looks like on QA:
<img width="1021" alt="Screenshot 2023-04-24 at 15 21 24" src="https://user-images.githubusercontent.com/2204224/234025354-5a3cb082-d475-4b8e-a7fa-205df41a5d1d.png">

2023-04-25 06:23 UTC, markhallen commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Surface withdrawal, deferral, and award summary cards on trainee record](https://trello.com/c/gBRwwptt/5352-s-surface-withdrawal-deferral-and-award-summary-cards-on-trainee-record)

2023-04-25 09:14 UTC, edwardhorsford approved these changes

2023-04-25 09:18 UTC, merged