[5454] Allow upload of csv with blank rows
DFE-Digital/register-trainee-teachers pull request #3272
Opened 2023-05-10 08:28 UTC by richardpattinson

### Context

Submitting a CSV with a blank row leads to the error message ”  must match a trainee record”.

However the csv file should instead be accepted.

### Changes proposed in this pull request

Add a guard method to ensure that a blank row csv is accepted.

### Guidance to review

Try to submit a blank row csv.

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [ ] Do we need to send any updates to DQT as part of the work in this PR?
- [ ] Does this PR need an ADR?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2023-05-10 08:38 UTC, markhallen requested changes

2023-05-10 08:38 UTC, markhallen commented on app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
> +          return false unless value.nil?
Using `blank?` here also covers empty strings ("").
```suggestion
          return false unless value.blank?
```

2023-05-10 08:38 UTC, markhallen commented on spec/services/bulk_update/recommendations_uploads/validate_csv_row_spec.rb
Can we also add a test for empty strings?

2023-05-11 09:50 UTC, claire-hughez commented
[TEST2.csv](https://github.com/DFE-Digital/register-trainee-teachers/files/11450719/TEST2.csv)
When I use this CSV in the deployment, it says:

3 trainees who will be recommended for QTS or EYTS
2 trainees who will not be recommended, as you did not give a date when they met the QTS or EYTS standards

However, it should not count '2 trainees' - there's no detail for them. It shouldn't be mentioned at all?

2023-05-12 12:08 UTC, merged