[800] Implement flash messages
DFE-Digital/register-trainee-teachers pull request #352
Opened 2021-01-05 16:32 UTC by AbigailMcP

### Context

https://trello.com/c/U8u99a02/800-m-add-flash-messages-to-service?menu=filter&filter=label:Dev

### Changes proposed in this pull request

This PR adds a flash message component and renders a flash message in certain controllers as per the list on the Trello card.

The confirm pages using the generic confirm controller should all have sensible flash messages, which are specific to what the user is confirming.

Two situations on the card list - reinstating a trainee and deleting a draft - have not been implemented yet.

<img width="1552" alt="Screenshot 2021-01-05 at 15 25 23" src="https://user-images.githubusercontent.com/18436946/103671861-689ec100-4f73-11eb-8540-21a5e7da081f.png">

### Guidance to review

- Go down the list of scenarios as stated in the Trello card and test that the correct flash message appears in the correct location on the next page.

2021-01-05 16:36 UTC, AbigailMcP commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] Add flash messages to service](https://trello.com/c/U8u99a02/800-m-add-flash-messages-to-service)

2021-01-06 10:47 UTC, edwardhorsford requested changes
Looking good so far! Some implementation comments:
* Would suggest we make a base component for `Notification banner` that matches / recreates the design system [Notification banner](https://design-system.service.gov.uk/components/notification-banner/#reacting-to-something-the-user-has-done).
* This supports more options than just flash messages, and we should aim to be feature complete (which means other services can use ours too. You can see the [raw template here](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/notification-banner/template.njk).
* Messages that respond to user input are meant to get focus when the page is loaded. If the banner is set to `success` this happens automatically with the design system component.
* I reckon we might then have a second `flash message` component that uses the `notification banner` and sets the appropriate option - including doing the looping that the current one is doing.

Probably not related to this pr, but I notice our 'return' url for lots of changes takes the user to completely the wrong place.

2021-01-06 11:44 UTC, darokel approved these changes
Code wise this looks good to me 👍

2021-01-06 11:44 UTC, darokel commented on app/components/flash_message/view.rb
> +    attr_reader :flash
I think this should be public since it's being used publicly by the html?

2021-01-06 11:45 UTC, darokel commented
> Looking good so far! Some implementation comments:
> 
> * Would suggest we make a base component for `Notification banner` that matches / recreates the design system [Notification banner](https://design-system.service.gov.uk/components/notification-banner/#reacting-to-something-the-user-has-done).
> * This supports more options than just flash messages, and we should aim to be feature complete (which means other services can use ours too. You can see the [raw template here](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/notification-banner/template.njk).
> * Messages that respond to user input are meant to get focus when the page is loaded. If the banner is set to `success` this happens automatically with the design system component.
> * I reckon we might then have a second `flash message` component that uses the `notification banner` and sets the appropriate option - including doing the looping that the current one is doing.
> 
> Probably not related to this pr, but I notice our 'return' url for lots of changes takes the user to completely the wrong place.

Is it worth dealing with that base component when the need arises? For now I think we just need a simple way of rendering a flash message. Could refactor when we need to re-use something a bit more generic. (I'm not the designer though!)

2021-01-06 12:21 UTC, AbigailMcP commented
> > Looking good so far! Some implementation comments:
> > 
> > * Would suggest we make a base component for `Notification banner` that matches / recreates the design system [Notification banner](https://design-system.service.gov.uk/components/notification-banner/#reacting-to-something-the-user-has-done).
> > * This supports more options than just flash messages, and we should aim to be feature complete (which means other services can use ours too. You can see the [raw template here](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/notification-banner/template.njk).
> > * Messages that respond to user input are meant to get focus when the page is loaded. If the banner is set to `success` this happens automatically with the design system component.
> > * I reckon we might then have a second `flash message` component that uses the `notification banner` and sets the appropriate option - including doing the looping that the current one is doing.
> > 
> > Probably not related to this pr, but I notice our 'return' url for lots of changes takes the user to completely the wrong place.
> 
> @edwardhorsford Is it worth dealing with that base component when the need arises? For now I think we just need a simple way of rendering a flash message. Could refactor when we need to re-use something a bit more generic. (I'm not the designer though!)

I don't mind adding in the generic component now - I don't see it being much work to pass through the various options to the my flash component.

2021-01-06 15:36 UTC, AbigailMcP commented
@edwardhorsford - this should be pretty feature complete now. The only thing you can't do (I ran out of steam) is pass html to the component.

@darokel - `NotificationBanner` is the new component that replicates functionality from https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/notification-banner/template.njk. Now `FlashBanner` (renamed from `FlashMessage`) just renders a simple `NotificationBanner`.

2021-01-06 15:54 UTC, edwardhorsford approved these changes

2021-01-06 15:54 UTC, edwardhorsford commented
Looking great @AbigailMcP!

2021-01-07 12:22 UTC, darokel commented on app/components/notification_banner/view.rb
> +      return "Success" if success_banner?
Might be a good idea to put these "success" "alert" type of strings into constants within the component if they're going to be asserted against?

2021-01-07 13:11 UTC, AbigailMcP commented
@darokel - pulled strings into constants 👌

2021-01-07 13:21 UTC, merged