[840] Withdraw a trainee on DTTP
DFE-Digital/register-trainee-teachers pull request #435
Opened 2021-01-26 13:35 UTC by AbigailMcP

### Context

This PR builds from @gpeng 's draft PR #432 , so should be reviewed once we're happy with the changes there.

https://trello.com/c/2qKHILWU/840-withdraw-on-dttp

### Changes proposed in this pull request

This PR includes:

- A `WithdrawJob`, called from the `ConfirmWithdrawalsController`, which queues up a:
- `Dttp::Withdraw` service, which makes a `patch` call to DTTP to set the trainee status to `deferred`

### Not included:
- I haven't transferred the trainee internally to `withdrawn` since the architecture for this is being decided in a separate ticket (when we move all state transitions out of jobs).

2021-01-26 14:06 UTC, darokel approved these changes
🚢

2021-01-27 08:22 UTC, dankmitchell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Withdraw on DTTP](https://trello.com/c/2qKHILWU/840-withdraw-on-dttp)

2021-01-28 09:00 UTC, gpeng requested changes
I've un-draftificated #432 now so this should be good to go. Just need to fix the args to `Dttp::Params::Status` as I've changed them.

2021-01-28 10:43 UTC, AbigailMcP commented
@gpeng - changes made, should be gtg now!

2021-01-28 16:54 UTC, gpeng approved these changes
I've merged #432 now so you should be able to rebase and merge.

![](https://media.giphy.com/media/U7P4U04shCFcBWcBwb/giphy.gif)

2021-01-29 10:58 UTC, merged