DRAFT: Migrating lead_school columns to lead_partner
DFE-Digital/register-trainee-teachers pull request #4551
Opened 2024-08-12 15:53 UTC by adamjcolvin

### Context

### Changes proposed in this pull request

### Guidance to review

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [ ] Do we need to send any updates to DQT as part of the work in this PR?
- [ ] Does this PR need an ADR?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

2024-08-16 12:46 UTC, kennyevil approved these changes

2024-08-16 14:57 UTC, defong requested changes
Not sure why we deleting this

`app/views/guidance/_schools.html.erb`

2024-08-16 14:57 UTC, defong commented on app/views/guidance/_schools.html.erb
I'm not sure this should be deleted?


'm pretty sure it is this page
https://www.register-trainee-teachers.service.gov.uk/guidance/hesa-register-data-mapping/schools

of which this link needs correcting from 
https://www.hesa.ac.uk/collection/c23053/e/sdlead
to
https://www.hesa.ac.uk/collection/c24053/e/sdlead

2024-08-16 16:02 UTC, defong commented on app/views/guidance/_schools.html.erb
This is now broken https://register-pr-4551.test.teacherservices.cloud/guidance/hesa-register-data-mapping/schools

Maybe we should add a test altogether :shrug:

2024-08-19 09:00 UTC, adamjcolvin commented
> Not sure why we deleting this
> 
> `app/views/guidance/_schools.html.erb`

@defong That's the same partial that was giving us problems after the last PR was merged. I'm not sure how the change crept in again but I've put it back now.

2024-08-19 09:23 UTC, adamjcolvin commented on app/views/guidance/_schools.html.erb
> +    <td class="govuk-table__cell"><a class="govuk-link" href="https://www.hesa.ac.uk/collection/c23053/e/sdlead">SDLEAD</a> (School Direct lead school)</td>
Done 👍

2024-08-19 09:50 UTC, defong approved these changes

2024-08-19 14:50 UTC, merged