[1020] Missing details component [WIP]
DFE-Digital/register-trainee-teachers pull request #521
Opened 2021-02-11 21:09 UTC by avinhurry

- Need refactor
- Need more tests
- Need content consistency check
- Need to fix degree start section link

### Context

### Changes proposed in this pull request

### Guidance to review

2021-02-11 21:15 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] Give the review record page component state (or another component)](https://trello.com/c/8bTmKcGX/1020-m-give-the-review-record-page-component-state-or-another-component)

2021-02-11 23:40 UTC, edwardhorsford requested changes

2021-02-11 23:40 UTC, edwardhorsford commented on app/components/missing_details/style.scss
> +}
@avinhurry can we review these? we shouldn't redefine govuk styles. I think we can probably make do with a modifier on the existing inset text component.

2021-02-17 11:21 UTC, defong commented
heroku issues

2021-02-18 09:19 UTC, defong commented
it evolved to #540

2021-02-18 09:19 UTC, closed without merging