[1166] Remove primary schools from universities list
DFE-Digital/register-trainee-teachers pull request #610
Opened 2021-03-04 11:29 UTC by avinhurry

### Context

There are Primary Schools in the universities list. We need to remove these.

2021-03-04 11:30 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [There's a school in the universities list 🙊](https://trello.com/c/20uBt2mA/1166-theres-a-school-in-the-universities-list-%F0%9F%99%8A)

2021-03-04 11:31 UTC, jhenderson requested changes

2021-03-04 11:31 UTC, jhenderson commented on app/lib/dttp/code_sets/institutions.rb
>          "Brindishe Green School" => { entity_id: "b14d7d29-a241-e811-80ff-3863bb351d40" },
I think we also need to get rid of "Brindishe Green School"

2021-03-04 17:05 UTC, jhenderson approved these changes

2021-03-05 08:00 UTC, defong approved these changes

2021-03-05 10:48 UTC, merged