[1257] Rename programme to course
DFE-Digital/register-trainee-teachers pull request #653
Opened 2021-03-12 16:13 UTC by dankmitchell

### Context
Programme is the wrong term. Course is better

### Changes proposed in this pull request
Rename `programme` to `course`

### Guidance to review
🚢 🙏

2021-03-12 16:14 UTC, dankmitchell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rename Programme details to course details](https://trello.com/c/DilDiLlt/1257-rename-programme-details-to-course-details)

2021-03-12 16:34 UTC, defong requested changes
https://rtt-review-pr-653.herokuapp.com/view_components/pages/trainees/check_details/view


https://rtt-review-pr-653.herokuapp.com/view_components/pages/trainees/check_details/view/confirmations_sections

Its all broken now

2021-03-15 12:39 UTC, defong approved these changes
Having a moan means everything is working again.

:sweat_smile:

2021-03-15 12:51 UTC, edwardhorsford approved these changes

2021-03-15 12:51 UTC, merged