1258 if redirected to sign in after sign in users should be returned to the page they requested
DFE-Digital/register-trainee-teachers pull request #672
Opened 2021-03-17 17:02 UTC by stellenberger

### Context

- [Trello ticket](https://trello.com/c/ARJr6uyX/1258-m-if-redirected-to-sign-in-after-sign-in-users-should-be-returned-to-the-page-they-requested)
- Currently, if users direct themselves to a path via a hyperlink or manually putting it in the search bar and they are not logged in, they will be redirected to sign in, and then redirected back to home/root page ("/"). 
- We want the original search query to be saved in the session and then loaded on redirect after the sign in, and then deleted off the session. 

### Changes proposed in this pull request

- New `save_redirect_path` method in application controller
- `save_redirect_path` will be called on unsuccessful authentication, along with a `redirect to sign_in_path`
- `save_redirect_path` will save the path in `session[:redirect_back_to]` for further use
- On successful `current_user` (final step of DSI journey) in `SessionsController` in `callback`, a conditional will check for the `session[:redirect_back_to]` link and use it once before deleting it. Fallback is `root_path`

### Guidance to review

- Log in and take an endpoint that you are sure is protected by authentication (perhaps "/trainees" or "/trainees/{trainee_slug}"). 
- Ensure you are logged out, and try and navigate to that endpoint. On redirect to sign in, sign in and you will find yourself redirected back to the original path from step 1.

2021-03-19 09:29 UTC, gpeng requested changes
Looks good @stellenberger. Just a couple of naming and clarity things 👍

2021-03-19 09:29 UTC, gpeng commented on app/controllers/sessions_controller.rb
> +      redirect_to(session[:redirect_back_to] ? session.delete(:redirect_back_to) : root_path)
```suggestion
      redirect_to session.delete(:redirect_back_to) || root_path
```
`Hash#delete` returns the value or `nil` if it isn't present.

2021-03-19 09:29 UTC, gpeng commented on app/controllers/application_controller.rb
> +  def save_redirect_path
I think the path is really the requested path rather than the redirect path. Would `save_requested_path` and `session[:requested_path]` be clearer?

2021-03-19 09:29 UTC, gpeng commented on app/controllers/application_controller.rb
> +    (save_redirect_path && (redirect_to sign_in_path)) unless authenticated?
Might be tidier to extract a method here. (or if you don't want to do that I don't think we need all the brackets).

```
save_requested_path_and_redirect unless authenticated?
```

and 

```
def save_requested_path_and_redirect
  save_requested_path
  redirect_to sign_in_path
end
```

2021-03-19 09:31 UTC, gpeng commented on app/controllers/application_controller.rb
> +  def save_redirect_path
Sorry.. just realised I called it `redirect_back_to` in the Trello ticket 🤦

2021-03-19 09:33 UTC, gpeng commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] If redirected to sign-in, after sign-in users should be returned to the page they requested](https://trello.com/c/ARJr6uyX/1258-m-if-redirected-to-sign-in-after-sign-in-users-should-be-returned-to-the-page-they-requested)

2021-03-23 10:10 UTC, gpeng approved these changes

2021-03-23 11:05 UTC, GeoffJohnson commented
All good to merge

2021-03-23 11:10 UTC, merged