[864] ADR 4 - non-integer trainee IDs
DFE-Digital/register-trainee-teachers pull request #729
Opened 2021-04-01 11:42 UTC by gpeng

### Context

We have ADRs. We didn't have one for this decision.

### Changes proposed in this pull request

* Add ADR for non-integer trainee IDs.

### Guidance to review

Read the thing... 😁

2021-04-01 11:44 UTC, gpeng commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add ADR for URL secure token stuff](https://trello.com/c/NeBcfC6u/864-add-adr-for-url-secure-token-stuff)

2021-04-06 07:41 UTC, defong requested changes
Please add to register-trainee-teachers/docs/adr/index.md

2021-04-06 08:36 UTC, defong requested changes

2021-04-06 08:36 UTC, defong commented on docs/adr/0004-non-integer-trainee-ids.md
> +Date: 1 April 2021
```suggestion
Date: 2021-04-01
```

https://github.com/DFE-Digital/register-trainee-teacher-data/blob/master/docs/adr/0001-record-architecture-decisions.md#L3

2021-04-06 08:36 UTC, defong commented on docs/adr/0004-non-integer-trainee-ids.md
> +* interoperability with other systems without depending on DB ids
```suggestion
* interoperability with other systems without depending on DB IDs
```

everywhere else is `IDs`

2021-04-06 08:36 UTC, defong commented on docs/adr/0004-non-integer-trainee-ids.md
> +- record now has two 'ids'
```suggestion
- record now has two 'IDs'
```

everywhere else is `IDs`

2021-04-06 08:36 UTC, defong commented on docs/adr/0004-non-integer-trainee-ids.md
> +Trainee URLs are no longer predicatable and we have an effectively unique identifier.
```suggestion
Trainee URLs are no longer predictable and we have an effective unique identifier.
```

2021-04-06 08:36 UTC, defong commented on docs/adr/template.md
> +Date: DATE
```suggestion
Date: YYYY-MM-DD
```

2021-04-06 09:42 UTC, defong approved these changes

2021-04-06 09:42 UTC, defong commented on docs/adr/0004-non-integer-trainee-ids.md
> +Use a 32 character UUID
```suggestion
Use a 32 characters UUID
```

2021-04-06 09:42 UTC, defong commented on docs/adr/0004-non-integer-trainee-ids.md
> +### 2. Continue using integers IDs
```suggestion
### 2. Continue using integer based IDs
```

2021-04-06 09:44 UTC, gpeng commented on docs/adr/0004-non-integer-trainee-ids.md
> +Use a 32 character UUID
'a 32 character' is correct...

2021-04-06 09:54 UTC, merged

2021-04-06 15:10 UTC, defong commented on docs/adr/0004-non-integer-trainee-ids.md
> +Use a 32 character UUID
¯\_(ツ)_/¯ it's just poor grammar in any case