[1652] Add apply trainee data page
DFE-Digital/register-trainee-teachers pull request #864
Opened 2021-05-11 08:39 UTC by FriedSock

### Context

https://trello.com/c/8aqWACnk/1652-m-apply-review-application-page

This page is similar to the check details page in that there will be
Subsections of data that come from an apply application. The difference
being that in a future iteration, there will be error validation that
will point the user to fields they need to correct, rather than just
being told a section is incomplete and having to navigate through
every step of the form.

Given the similarities with the check details page (and trn submission
Form), I tried to share some behaviour between them, but decided to go
for a bit of copying until we add more functionality, namely:
- Error checking on the apply trainee data page
- Apply draft version of the check details page

### Changes proposed in this pull request

- Adds a new page for apply trainee data (to be linked from the review-draft page for apply draft trainees, containing sections for personal details, contact details, diversity, degrees
- Sets this page as an origin in the page tracker, so change links into the subsections will return to this page
- If the checkbox "I have reviewed this" is checked, all 4 sections are completed.

### Guidance to review

- Create a draft trainee with some data for the above 4 sections
- visit `/trainees/{trainee_id}/apply-trainee-data/edit`
- try changing attributes and check that you are returned to the page
- try submitting the form with/without checking the "I have reviewed" checkbox

2021-05-11 09:12 UTC, FriedSock commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] Apply review application page](https://trello.com/c/8aqWACnk/1652-m-apply-review-application-page)

2021-05-11 15:02 UTC, FriedSock commented
> https://rtt-review-pr-864.herokuapp.com/trainees/DgUN2p75ksioX2AEgEzDPuC2/apply-trainee-data/edit
> 
> ![image](https://user-images.githubusercontent.com/470137/117816604-961bb400-b25e-11eb-8a66-63cce6c8d6cc.png)
> 
> Should it be showing this

fixed

2021-05-11 15:08 UTC, FriedSock commented on app/controllers/trainees/apply_trainee_data_controller.rb
> +      redirect_to trainee_path(trainee)
It works in the same way as confirming sections, we confirm things based on that checkbox being submitted, othwerwise just go back to the review-draft page.

2021-05-12 09:01 UTC, defong requested changes
The `form`, ie `ApplyTraineeDataForm`, `TrnSubmissionForm`, should do all the hard work of making `Trainees::Sections::View` show the correct underlaying confirmation view or incomplete view for the respective section.

See https://en.wikipedia.org/wiki/Mediator_pattern

2021-05-12 09:01 UTC, defong commented on app/components/trainees/apply_trainee_data/view.html.erb
> +    <%= render Trainees::Sections::View.new(trainee: @trainee, form: @form, section: :degrees, show_incomplete: true) %>
As `delete` is an option 
![image](https://user-images.githubusercontent.com/470137/117947860-7d67d880-b308-11eb-840d-19113e952c96.png)

It now looks weird 
![image](https://user-images.githubusercontent.com/470137/117947960-98d2e380-b308-11eb-863a-cc20bf6b3593.png)

2021-05-13 12:59 UTC, FriedSock commented
Closing to try and retrigger a migration on the review app

2021-05-13 13:32 UTC, defong approved these changes

2021-05-13 13:33 UTC, merged

2021-05-14 11:18 UTC, GeoffJohnson commented
All good