[1868] Add back links to non-js schools pages
DFE-Digital/register-trainee-teachers pull request #931
Opened 2021-06-01 17:13 UTC by JonF1

### Context
* https://trello.com/c/gNixYYfb/1868-s-non-javascript-search-no-back-link

### Changes proposed in this pull request
Add back links to both employing schools and lead schools non-js index views
Backlinks take user back to edit pages
### Guidance to review
Create both lead and employing schools in you db with FactoryBot

2021-06-01 19:07 UTC, JonF1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Non-javascript search no back link](https://trello.com/c/gNixYYfb/1868-s-non-javascript-search-no-back-link)

2021-06-02 11:12 UTC, darokel approved these changes

2021-06-02 12:08 UTC, darokel requested changes
Just checked again and noticed on the employing school page the back link goes back to the review-draft page. Think it should go back to the lead school search

![Screen Recording (Google Chrome)](https://user-images.githubusercontent.com/616080/120477379-9d3c6a80-c3a3-11eb-9eb6-d18a4c19382a.gif)

2021-06-02 20:36 UTC, JonF1 commented on app/controllers/trainees/lead_schools_controller.rb
> +      origin_page << "/trainees/#{trainee.slug}/#{trainee.employing_school.nil? ? 'review-draft' : 'schools/confirm'}".to_s
😭

2021-06-02 21:11 UTC, JonF1 commented
> Just checked again and noticed on the employing school page the back link goes back to the review-draft page. Think it should go back to the lead school search

Cheers, should be ready for re-review

2021-06-03 16:33 UTC, darokel approved these changes

2021-06-07 09:21 UTC, edwardhorsford approved these changes

2021-06-07 11:24 UTC, merged