[1851] EY - Remove subject and age range from course details form
DFE-Digital/register-trainee-teachers pull request #968
Opened 2021-06-07 16:03 UTC by mooktakim

### Context

https://trello.com/c/77dx3rGp/1851-s-ey-remove-subject-and-age-range-from-course-details-form

### Changes proposed in this pull request

* Updated course details form to hide subject and age range for early years routes

### Guidance to review

2021-06-07 16:04 UTC, mooktakim commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] EY - Remove subject and age range from course details form](https://trello.com/c/77dx3rGp/1851-s-ey-remove-subject-and-age-range-from-course-details-form)

2021-06-08 08:05 UTC, defong requested changes

2021-06-08 08:05 UTC, defong commented on spec/lib/training_route_manager_spec.rb
> +      end
```suggestion
      it "returns false" do
        expect(subject.early_years_route?).to be false
      end
```

2021-06-08 09:13 UTC, defong commented on app/components/trainees/confirmation/course_details/view.rb
> +            ({ key: t("components.course_detail.age_range"), value: course_age_range, action: action_link("age range") } if require_age_range?),
```suggestion
            *({ key: t("components.course_detail.subject"), value: subject, action: action_link("subject") } if require_subject?),
            *({ key: t("components.course_detail.age_range"), value: course_age_range, action: action_link("age range") } if require_age_range?),
```


![image](https://user-images.githubusercontent.com/470137/121158151-0c054200-c842-11eb-82ad-30776d2ea4a8.png)



Then you can drop compact

2021-06-08 09:17 UTC, defong approved these changes

2021-06-09 08:06 UTC, GeoffJohnson commented
All good

2021-06-09 09:54 UTC, merged