[1855] Change title on outcome date edit page for early years trainees
DFE-Digital/register-trainee-teachers pull request #978
Opened 2021-06-08 17:06 UTC by avinhurry

### Context

The title on the outcome date edit page, for early year trainees is being changed. 
The title on the same page for non early year trainees is also being updated.  

### Guidance to review

- Navigate to a non early year trainee with a status of `TRN received`, click the green `Recommend trainee for QTS` button and check that the page title and heading now says `When did they meet the QTS standards?`

- Navigate to an early year trainee with a status of `TRN received`, click the green `Recommend trainee for QTS` button and check that the page title and heading now says `When did they meet the EYTS standards?`

### Screenshots

![image](https://user-images.githubusercontent.com/50492247/121227937-0f212200-c884-11eb-9da6-84d2fe87f258.png)
![image](https://user-images.githubusercontent.com/50492247/121227981-1c3e1100-c884-11eb-8c10-1417f215ffb8.png)

2021-06-08 17:07 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] EY - Recommend for EYTS form heading - 'When did they meet the EYTS standards'](https://trello.com/c/EpNpjmxn/1855-s-ey-recommend-for-eyts-form-heading-when-did-they-meet-the-eyts-standards)

2021-06-09 09:57 UTC, mooktakim requested changes

2021-06-09 09:57 UTC, mooktakim commented on app/views/trainees/outcome_dates/edit.html.erb
> +<% text = @trainee.is_early_years? ? I18n.t("components.page_titles.trainees.outcome_date.eyts_edit") : I18n.t("components.page_titles.trainees.outcome_date.edit") %>
`text` variable is better as a method on `view.rb`

2021-06-09 10:06 UTC, mooktakim approved these changes
Looks good!

2021-06-09 10:51 UTC, merged