[1932] Course details form persists course_code if exists
DFE-Digital/register-trainee-teachers pull request #982
Opened 2021-06-09 11:18 UTC by stellenberger

### Context

- [This trello ticket](https://trello.com/c/OiYr9UZr/1932-m-when-you-edit-the-details-fro-a-publish-course-it-forgets-that-its-a-publish-course)

### Changes proposed in this pull request

- `course_code` param in the form was being set to nil, but there was a `course_code` method already implemented which persists the trainee course code. I set the params to use this `course_code` method

### Guidance to review

- Create a trainee on a Provider Led Postgrad route
- Assign them to a Publish Course
- Confirm the course
- Change that course subject
- The publish course will now not be wiped and the course will persist on the next confirm page, with the new subject attached to the trainee

2021-06-09 11:19 UTC, stellenberger commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] When you edit the details fro a publish course it forgets that it’s a publish course](https://trello.com/c/OiYr9UZr/1932-m-when-you-edit-the-details-fro-a-publish-course-it-forgets-that-its-a-publish-course)

2021-06-09 11:45 UTC, archferns reviewed
Looks good, but wondering it would be better to have a [unit spec](https://github.com/DFE-Digital/register-trainee-teachers/blob/1932-when-you-edit-the-details-fro-a-publish-course-it-forgets-that-its-a-publish-course/spec/forms/course_detail_form_spec.rb) instead of a controller spec?

2021-06-09 13:03 UTC, darokel requested changes

2021-06-09 13:03 UTC, darokel commented on app/forms/course_details_form.rb
> +      course_code: course_code,
We still want to set this to nil if the "Another course not listed" option has been selected then the course code is redundant in that scenario

2021-06-11 09:32 UTC, darokel commented on spec/forms/course_detail_form_spec.rb
> +        it "doesnt wipe course code" do
can we space this and move the `subject.save` and `trainee.reload` into a before block to organise

2021-06-11 09:33 UTC, darokel approved these changes
one little cosmetic comment but all good

2021-06-14 14:02 UTC, GeoffJohnson commented
All good

2021-06-14 14:04 UTC, merged